import dayjs from 'dayjs/esm';

import { EnumFieldClass } from 'app/entities/enumerations/enum-field-class.model';
import { EnumRequiredFieldClass } from 'app/entities/enumerations/enum-required-field-class.model';

import { IFieldTestInfiniteScrollEntity, NewFieldTestInfiniteScrollEntity } from './field-test-infinite-scroll-entity.model';

export const sampleWithRequiredData: IFieldTestInfiniteScrollEntity = {
  id: 25098,
  stringRequiredHugo: 'kindly by considering',
  integerRequiredHugo: 1658,
  longRequiredHugo: 8658,
  floatRequiredHugo: 19011.43,
  doubleRequiredHugo: 31453.43,
  bigDecimalRequiredHugo: 25392.55,
  localDateRequiredHugo: dayjs('2016-02-08'),
  instanteRequiredHugo: dayjs('2016-02-07T22:56'),
  zonedDateTimeRequiredHugo: dayjs('2016-02-08T11:27'),
  localTimeRequiredHugo: '00:04:00',
  durationRequiredHugo: '12656',
  booleanRequiredHugo: true,
  enumRequiredHugo: 'ENUM_VALUE_1',
  uuidRequiredHugo: '8aa18dc2-28fd-4944-8438-b73895b16d22',
  byteImageRequiredHugo: '../fake-data/blob/hipster.png',
  byteImageRequiredHugoContentType: 'unknown',
  byteAnyRequiredHugo: '../fake-data/blob/hipster.png',
  byteAnyRequiredHugoContentType: 'unknown',
  byteTextRequiredHugo: '../fake-data/blob/hipster.txt',
};

export const sampleWithPartialData: IFieldTestInfiniteScrollEntity = {
  id: 3428,
  stringHugo: 'seemingly within yuck',
  stringRequiredHugo: 'abaft',
  stringPatternHugo: undefined,
  integerHugo: 3126,
  integerRequiredHugo: 17031,
  integerMaxHugo: 60,
  longHugo: 20545,
  longRequiredHugo: 6634,
  longMinHugo: 14164,
  floatRequiredHugo: 27957.4,
  floatMaxHugo: 29.11,
  doubleRequiredHugo: 3660.56,
  doubleMinHugo: 22073.26,
  doubleMaxHugo: 86.05,
  bigDecimalRequiredHugo: 20035.43,
  bigDecimalMinHugo: 20857.09,
  bigDecimalMaxHugo: 95.47,
  localDateHugo: dayjs('2016-02-08'),
  localDateRequiredHugo: dayjs('2016-02-08'),
  instanteRequiredHugo: dayjs('2016-02-08T16:52'),
  zonedDateTimeRequiredHugo: dayjs('2016-02-08T06:26'),
  localTimeRequiredHugo: '22:30:00',
  durationHugo: '20565',
  durationRequiredHugo: '11604',
  booleanHugo: true,
  booleanRequiredHugo: false,
  enumRequiredHugo: 'ENUM_VALUE_3',
  uuidRequiredHugo: 'b8df1721-7f15-4f46-851c-8705b950e7e7',
  byteImageHugo: '../fake-data/blob/hipster.png',
  byteImageHugoContentType: 'unknown',
  byteImageRequiredHugo: '../fake-data/blob/hipster.png',
  byteImageRequiredHugoContentType: 'unknown',
  byteImageMinbytesHugo: '../fake-data/blob/hipster.png',
  byteImageMinbytesHugoContentType: 'unknown',
  byteImageMaxbytesHugo: '../fake-data/blob/hipster.png',
  byteImageMaxbytesHugoContentType: 'unknown',
  byteAnyRequiredHugo: '../fake-data/blob/hipster.png',
  byteAnyRequiredHugoContentType: 'unknown',
  byteAnyMinbytesHugo: '../fake-data/blob/hipster.png',
  byteAnyMinbytesHugoContentType: 'unknown',
  byteTextHugo: '../fake-data/blob/hipster.txt',
  byteTextRequiredHugo: '../fake-data/blob/hipster.txt',
};

export const sampleWithFullData: IFieldTestInfiniteScrollEntity = {
  id: 26510,
  stringHugo: 'condense and hence',
  stringRequiredHugo: 'courageously boastfully',
  stringMinlengthHugo: 'pish besides',
  stringMaxlengthHugo: 'concerning',
  stringPatternHugo: 'X',
  integerHugo: 15075,
  integerRequiredHugo: 25566,
  integerMinHugo: 8400,
  integerMaxHugo: 51,
  longHugo: 24329,
  longRequiredHugo: 4839,
  longMinHugo: 4213,
  longMaxHugo: 62,
  floatHugo: 16632.51,
  floatRequiredHugo: 31216.69,
  floatMinHugo: 30762.99,
  floatMaxHugo: 59.13,
  doubleRequiredHugo: 16070.73,
  doubleMinHugo: 18624.71,
  doubleMaxHugo: 77.6,
  bigDecimalRequiredHugo: 19163.88,
  bigDecimalMinHugo: 9108.83,
  bigDecimalMaxHugo: 83.38,
  localDateHugo: dayjs('2016-02-08'),
  localDateRequiredHugo: dayjs('2016-02-08'),
  instantHugo: dayjs('2016-02-08T05:13'),
  instanteRequiredHugo: dayjs('2016-02-08T09:22'),
  zonedDateTimeHugo: dayjs('2016-02-07T21:15'),
  zonedDateTimeRequiredHugo: dayjs('2016-02-07T21:02'),
  localTimeHugo: '23:43:00',
  localTimeRequiredHugo: '10:09:00',
  durationHugo: '13542',
  durationRequiredHugo: '16754',
  booleanHugo: false,
  booleanRequiredHugo: false,
  enumHugo: 'ENUM_VALUE_3',
  enumRequiredHugo: 'ENUM_VALUE_1',
  uuidHugo: '978fd260-8d93-4d51-b6d4-1681c0c3ef01',
  uuidRequiredHugo: 'c952d397-a9bc-4d3f-b94d-5041a1356699',
  byteImageHugo: '../fake-data/blob/hipster.png',
  byteImageHugoContentType: 'unknown',
  byteImageRequiredHugo: '../fake-data/blob/hipster.png',
  byteImageRequiredHugoContentType: 'unknown',
  byteImageMinbytesHugo: '../fake-data/blob/hipster.png',
  byteImageMinbytesHugoContentType: 'unknown',
  byteImageMaxbytesHugo: '../fake-data/blob/hipster.png',
  byteImageMaxbytesHugoContentType: 'unknown',
  byteAnyHugo: '../fake-data/blob/hipster.png',
  byteAnyHugoContentType: 'unknown',
  byteAnyRequiredHugo: '../fake-data/blob/hipster.png',
  byteAnyRequiredHugoContentType: 'unknown',
  byteAnyMinbytesHugo: '../fake-data/blob/hipster.png',
  byteAnyMinbytesHugoContentType: 'unknown',
  byteAnyMaxbytesHugo: '../fake-data/blob/hipster.png',
  byteAnyMaxbytesHugoContentType: 'unknown',
  byteTextHugo: '../fake-data/blob/hipster.txt',
  byteTextRequiredHugo: '../fake-data/blob/hipster.txt',
};

export const sampleWithNewData: NewFieldTestInfiniteScrollEntity = {
  stringRequiredHugo: 'quit readmit',
  integerRequiredHugo: 975,
  longRequiredHugo: 8348,
  floatRequiredHugo: 25965.42,
  doubleRequiredHugo: 15620.25,
  bigDecimalRequiredHugo: 22309.01,
  localDateRequiredHugo: dayjs('2016-02-08'),
  instanteRequiredHugo: dayjs('2016-02-07T21:14'),
  zonedDateTimeRequiredHugo: dayjs('2016-02-08T08:53'),
  localTimeRequiredHugo: '15:47:00',
  durationRequiredHugo: '17009',
  booleanRequiredHugo: false,
  enumRequiredHugo: 'ENUM_VALUE_1',
  uuidRequiredHugo: '960b40c8-49c7-42f2-8360-f2f6ab2ba375',
  byteImageRequiredHugo: '../fake-data/blob/hipster.png',
  byteImageRequiredHugoContentType: 'unknown',
  byteAnyRequiredHugo: '../fake-data/blob/hipster.png',
  byteAnyRequiredHugoContentType: 'unknown',
  byteTextRequiredHugo: '../fake-data/blob/hipster.txt',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
