# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
---
spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    username: sampleWebfluxH2mem
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    username: sampleWebfluxH2mem
    password:
