import dayjs from 'dayjs/esm';

import { EnumFieldClass } from 'app/entities/enumerations/enum-field-class.model';
import { EnumRequiredFieldClass } from 'app/entities/enumerations/enum-required-field-class.model';

import { IFieldTestEntity, NewFieldTestEntity } from './field-test-entity.model';

export const sampleWithRequiredData: IFieldTestEntity = {
  id: 8114,
  stringRequiredTom: 'carelessly',
  numberPatternRequiredTom: '454908',
  integerRequiredTom: 23312,
  longRequiredTom: 13804,
  floatRequiredTom: 3728.91,
  doubleRequiredTom: 2702.26,
  bigDecimalRequiredTom: 24954.84,
  localDateRequiredTom: dayjs('2016-02-08'),
  instantRequiredTom: dayjs('2016-02-07T22:13'),
  zonedDateTimeRequiredTom: dayjs('2016-02-08T11:56'),
  localTimeRequiredTom: '12:21:00',
  durationRequiredTom: '18734',
  booleanRequiredTom: true,
  enumRequiredTom: 'ENUM_VALUE_3',
  uuidRequiredTom: '336aaa22-f8c0-46b0-90c0-258fd1fd388b',
  byteImageRequiredTom: '../fake-data/blob/hipster.png',
  byteImageRequiredTomContentType: 'unknown',
  byteAnyRequiredTom: '../fake-data/blob/hipster.png',
  byteAnyRequiredTomContentType: 'unknown',
  byteTextRequiredTom: '../fake-data/blob/hipster.txt',
};

export const sampleWithPartialData: IFieldTestEntity = {
  id: 16316,
  stringRequiredTom: 'never pfft conclude',
  stringMinlengthTom: 'noxious stitcher',
  stringPatternTom: 'bP8D',
  numberPatternTom: '17',
  numberPatternRequiredTom: '4',
  integerRequiredTom: 7463,
  integerMinTom: 31370,
  integerMaxTom: 73,
  longRequiredTom: 20684,
  longMaxTom: 98,
  floatTom: 9230.41,
  floatRequiredTom: 3549.83,
  floatMinTom: 18779.08,
  floatMaxTom: 52.1,
  doubleRequiredTom: 18365.11,
  bigDecimalRequiredTom: 20449.32,
  bigDecimalMinTom: 18959.27,
  bigDecimalMaxTom: 34.93,
  localDateTom: dayjs('2016-02-08'),
  localDateRequiredTom: dayjs('2016-02-08'),
  instantTom: dayjs('2016-02-08T13:59'),
  instantRequiredTom: dayjs('2016-02-08T03:09'),
  zonedDateTimeTom: dayjs('2016-02-08T01:29'),
  zonedDateTimeRequiredTom: dayjs('2016-02-08T13:28'),
  localTimeRequiredTom: '09:27:00',
  durationRequiredTom: '5003',
  booleanTom: true,
  booleanRequiredTom: false,
  enumTom: 'ENUM_VALUE_3',
  enumRequiredTom: 'ENUM_VALUE_2',
  uuidTom: '8e8b1608-3aca-464a-be38-a390bc374432',
  uuidRequiredTom: '13b1b6a3-334d-419f-acbe-ae113093329b',
  byteImageTom: '../fake-data/blob/hipster.png',
  byteImageTomContentType: 'unknown',
  byteImageRequiredTom: '../fake-data/blob/hipster.png',
  byteImageRequiredTomContentType: 'unknown',
  byteImageMinbytesTom: '../fake-data/blob/hipster.png',
  byteImageMinbytesTomContentType: 'unknown',
  byteImageMaxbytesTom: '../fake-data/blob/hipster.png',
  byteImageMaxbytesTomContentType: 'unknown',
  byteAnyTom: '../fake-data/blob/hipster.png',
  byteAnyTomContentType: 'unknown',
  byteAnyRequiredTom: '../fake-data/blob/hipster.png',
  byteAnyRequiredTomContentType: 'unknown',
  byteAnyMaxbytesTom: '../fake-data/blob/hipster.png',
  byteAnyMaxbytesTomContentType: 'unknown',
  byteTextTom: '../fake-data/blob/hipster.txt',
  byteTextRequiredTom: '../fake-data/blob/hipster.txt',
};

export const sampleWithFullData: IFieldTestEntity = {
  id: 4913,
  stringTom: 'meatloaf',
  stringRequiredTom: 'deliberately',
  stringMinlengthTom: 'airline reasoning hm',
  stringMaxlengthTom: 'convoke reschedule',
  stringPatternTom: 'Pr4kL',
  numberPatternTom: '537522',
  numberPatternRequiredTom: '255072',
  integerTom: 19800,
  integerRequiredTom: 16368,
  integerMinTom: 3105,
  integerMaxTom: 36,
  longTom: 4743,
  longRequiredTom: 28122,
  longMinTom: 25355,
  longMaxTom: 6,
  floatTom: 152.02,
  floatRequiredTom: 13986.01,
  floatMinTom: 1217.01,
  floatMaxTom: 10.56,
  doubleRequiredTom: 7261.92,
  doubleMinTom: 26434.39,
  doubleMaxTom: 37.88,
  bigDecimalRequiredTom: 926.73,
  bigDecimalMinTom: 20504.41,
  bigDecimalMaxTom: 2.92,
  localDateTom: dayjs('2016-02-07'),
  localDateRequiredTom: dayjs('2016-02-08'),
  instantTom: dayjs('2016-02-08T17:31'),
  instantRequiredTom: dayjs('2016-02-08T06:06'),
  zonedDateTimeTom: dayjs('2016-02-08T07:31'),
  zonedDateTimeRequiredTom: dayjs('2016-02-08T10:20'),
  localTimeTom: '13:30:00',
  localTimeRequiredTom: '04:04:00',
  durationTom: '16601',
  durationRequiredTom: '26878',
  booleanTom: true,
  booleanRequiredTom: false,
  enumTom: 'ENUM_VALUE_3',
  enumRequiredTom: 'ENUM_VALUE_1',
  uuidTom: 'dd969db6-89b2-4778-b9bf-73a74b64bc0d',
  uuidRequiredTom: '0e1d9265-5336-4b6d-9015-b4c2e1fd3257',
  byteImageTom: '../fake-data/blob/hipster.png',
  byteImageTomContentType: 'unknown',
  byteImageRequiredTom: '../fake-data/blob/hipster.png',
  byteImageRequiredTomContentType: 'unknown',
  byteImageMinbytesTom: '../fake-data/blob/hipster.png',
  byteImageMinbytesTomContentType: 'unknown',
  byteImageMaxbytesTom: '../fake-data/blob/hipster.png',
  byteImageMaxbytesTomContentType: 'unknown',
  byteAnyTom: '../fake-data/blob/hipster.png',
  byteAnyTomContentType: 'unknown',
  byteAnyRequiredTom: '../fake-data/blob/hipster.png',
  byteAnyRequiredTomContentType: 'unknown',
  byteAnyMinbytesTom: '../fake-data/blob/hipster.png',
  byteAnyMinbytesTomContentType: 'unknown',
  byteAnyMaxbytesTom: '../fake-data/blob/hipster.png',
  byteAnyMaxbytesTomContentType: 'unknown',
  byteTextTom: '../fake-data/blob/hipster.txt',
  byteTextRequiredTom: '../fake-data/blob/hipster.txt',
};

export const sampleWithNewData: NewFieldTestEntity = {
  stringRequiredTom: 'bad',
  numberPatternRequiredTom: '249',
  integerRequiredTom: 941,
  longRequiredTom: 12814,
  floatRequiredTom: 20641.01,
  doubleRequiredTom: 24240.67,
  bigDecimalRequiredTom: 18827.43,
  localDateRequiredTom: dayjs('2016-02-08'),
  instantRequiredTom: dayjs('2016-02-07T20:25'),
  zonedDateTimeRequiredTom: dayjs('2016-02-08T07:09'),
  localTimeRequiredTom: '22:04:00',
  durationRequiredTom: '13761',
  booleanRequiredTom: true,
  enumRequiredTom: 'ENUM_VALUE_3',
  uuidRequiredTom: '3f424260-f0f4-42a5-8a35-3e7b64f48daa',
  byteImageRequiredTom: '../fake-data/blob/hipster.png',
  byteImageRequiredTomContentType: 'unknown',
  byteAnyRequiredTom: '../fake-data/blob/hipster.png',
  byteAnyRequiredTomContentType: 'unknown',
  byteTextRequiredTom: '../fake-data/blob/hipster.txt',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
