package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityWithServiceImplAndPaginationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplAndPaginationAllPropertiesEquals(
        EntityWithServiceImplAndPagination expected,
        EntityWithServiceImplAndPagination actual
    ) {
        assertEntityWithServiceImplAndPaginationAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityWithServiceImplAndPaginationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplAndPaginationAllUpdatablePropertiesEquals(
        EntityWithServiceImplAndPagination expected,
        EntityWithServiceImplAndPagination actual
    ) {
        assertEntityWithServiceImplAndPaginationUpdatableFieldsEquals(expected, actual);
        assertEntityWithServiceImplAndPaginationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplAndPaginationAutoGeneratedPropertiesEquals(
        EntityWithServiceImplAndPagination expected,
        EntityWithServiceImplAndPagination actual
    ) {
        assertThat(actual)
            .as("Verify EntityWithServiceImplAndPagination auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplAndPaginationUpdatableFieldsEquals(
        EntityWithServiceImplAndPagination expected,
        EntityWithServiceImplAndPagination actual
    ) {
        assertThat(actual)
            .as("Verify EntityWithServiceImplAndPagination relevant properties")
            .satisfies(a -> assertThat(a.getHugo()).as("check hugo").isEqualTo(expected.getHugo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplAndPaginationUpdatableRelationshipsEquals(
        EntityWithServiceImplAndPagination expected,
        EntityWithServiceImplAndPagination actual
    ) {
        // empty method
    }
}
