package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityWithDTOAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithDTOAllPropertiesEquals(EntityWithDTO expected, EntityWithDTO actual) {
        assertEntityWithDTOAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityWithDTOAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithDTOAllUpdatablePropertiesEquals(EntityWithDTO expected, EntityWithDTO actual) {
        assertEntityWithDTOUpdatableFieldsEquals(expected, actual);
        assertEntityWithDTOUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithDTOAutoGeneratedPropertiesEquals(EntityWithDTO expected, EntityWithDTO actual) {
        assertThat(actual)
            .as("Verify EntityWithDTO auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithDTOUpdatableFieldsEquals(EntityWithDTO expected, EntityWithDTO actual) {
        assertThat(actual)
            .as("Verify EntityWithDTO relevant properties")
            .satisfies(a -> assertThat(a.getEmma()).as("check emma").isEqualTo(expected.getEmma()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithDTOUpdatableRelationshipsEquals(EntityWithDTO expected, EntityWithDTO actual) {
        // empty method
    }
}
