package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityWithServiceClassAndPaginationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceClassAndPaginationAllPropertiesEquals(
        EntityWithServiceClassAndPagination expected,
        EntityWithServiceClassAndPagination actual
    ) {
        assertEntityWithServiceClassAndPaginationAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityWithServiceClassAndPaginationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceClassAndPaginationAllUpdatablePropertiesEquals(
        EntityWithServiceClassAndPagination expected,
        EntityWithServiceClassAndPagination actual
    ) {
        assertEntityWithServiceClassAndPaginationUpdatableFieldsEquals(expected, actual);
        assertEntityWithServiceClassAndPaginationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceClassAndPaginationAutoGeneratedPropertiesEquals(
        EntityWithServiceClassAndPagination expected,
        EntityWithServiceClassAndPagination actual
    ) {
        assertThat(actual)
            .as("Verify EntityWithServiceClassAndPagination auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceClassAndPaginationUpdatableFieldsEquals(
        EntityWithServiceClassAndPagination expected,
        EntityWithServiceClassAndPagination actual
    ) {
        assertThat(actual)
            .as("Verify EntityWithServiceClassAndPagination relevant properties")
            .satisfies(a -> assertThat(a.getEnzo()).as("check enzo").isEqualTo(expected.getEnzo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceClassAndPaginationUpdatableRelationshipsEquals(
        EntityWithServiceClassAndPagination expected,
        EntityWithServiceClassAndPagination actual
    ) {
        // empty method
    }
}
