package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityWithPaginationAndDTOAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithPaginationAndDTOAllPropertiesEquals(
        EntityWithPaginationAndDTO expected,
        EntityWithPaginationAndDTO actual
    ) {
        assertEntityWithPaginationAndDTOAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityWithPaginationAndDTOAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithPaginationAndDTOAllUpdatablePropertiesEquals(
        EntityWithPaginationAndDTO expected,
        EntityWithPaginationAndDTO actual
    ) {
        assertEntityWithPaginationAndDTOUpdatableFieldsEquals(expected, actual);
        assertEntityWithPaginationAndDTOUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithPaginationAndDTOAutoGeneratedPropertiesEquals(
        EntityWithPaginationAndDTO expected,
        EntityWithPaginationAndDTO actual
    ) {
        assertThat(actual)
            .as("Verify EntityWithPaginationAndDTO auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithPaginationAndDTOUpdatableFieldsEquals(
        EntityWithPaginationAndDTO expected,
        EntityWithPaginationAndDTO actual
    ) {
        assertThat(actual)
            .as("Verify EntityWithPaginationAndDTO relevant properties")
            .satisfies(a -> assertThat(a.getLea()).as("check lea").isEqualTo(expected.getLea()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithPaginationAndDTOUpdatableRelationshipsEquals(
        EntityWithPaginationAndDTO expected,
        EntityWithPaginationAndDTO actual
    ) {
        // empty method
    }
}
