package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityWithServiceClassPaginationAndDTOAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceClassPaginationAndDTOAllPropertiesEquals(
        EntityWithServiceClassPaginationAndDTO expected,
        EntityWithServiceClassPaginationAndDTO actual
    ) {
        assertEntityWithServiceClassPaginationAndDTOAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityWithServiceClassPaginationAndDTOAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceClassPaginationAndDTOAllUpdatablePropertiesEquals(
        EntityWithServiceClassPaginationAndDTO expected,
        EntityWithServiceClassPaginationAndDTO actual
    ) {
        assertEntityWithServiceClassPaginationAndDTOUpdatableFieldsEquals(expected, actual);
        assertEntityWithServiceClassPaginationAndDTOUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceClassPaginationAndDTOAutoGeneratedPropertiesEquals(
        EntityWithServiceClassPaginationAndDTO expected,
        EntityWithServiceClassPaginationAndDTO actual
    ) {
        assertThat(actual)
            .as("Verify EntityWithServiceClassPaginationAndDTO auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceClassPaginationAndDTOUpdatableFieldsEquals(
        EntityWithServiceClassPaginationAndDTO expected,
        EntityWithServiceClassPaginationAndDTO actual
    ) {
        assertThat(actual)
            .as("Verify EntityWithServiceClassPaginationAndDTO relevant properties")
            .satisfies(a -> assertThat(a.getLena()).as("check lena").isEqualTo(expected.getLena()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceClassPaginationAndDTOUpdatableRelationshipsEquals(
        EntityWithServiceClassPaginationAndDTO expected,
        EntityWithServiceClassPaginationAndDTO actual
    ) {
        // empty method
    }
}
