package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityWithServiceImplPaginationAndDTOAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplPaginationAndDTOAllPropertiesEquals(
        EntityWithServiceImplPaginationAndDTO expected,
        EntityWithServiceImplPaginationAndDTO actual
    ) {
        assertEntityWithServiceImplPaginationAndDTOAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityWithServiceImplPaginationAndDTOAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplPaginationAndDTOAllUpdatablePropertiesEquals(
        EntityWithServiceImplPaginationAndDTO expected,
        EntityWithServiceImplPaginationAndDTO actual
    ) {
        assertEntityWithServiceImplPaginationAndDTOUpdatableFieldsEquals(expected, actual);
        assertEntityWithServiceImplPaginationAndDTOUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplPaginationAndDTOAutoGeneratedPropertiesEquals(
        EntityWithServiceImplPaginationAndDTO expected,
        EntityWithServiceImplPaginationAndDTO actual
    ) {
        assertThat(actual)
            .as("Verify EntityWithServiceImplPaginationAndDTO auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplPaginationAndDTOUpdatableFieldsEquals(
        EntityWithServiceImplPaginationAndDTO expected,
        EntityWithServiceImplPaginationAndDTO actual
    ) {
        assertThat(actual)
            .as("Verify EntityWithServiceImplPaginationAndDTO relevant properties")
            .satisfies(a -> assertThat(a.getTheo()).as("check theo").isEqualTo(expected.getTheo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplPaginationAndDTOUpdatableRelationshipsEquals(
        EntityWithServiceImplPaginationAndDTO expected,
        EntityWithServiceImplPaginationAndDTO actual
    ) {
        // empty method
    }
}
