package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntityWithServiceImplAndDTOAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplAndDTOAllPropertiesEquals(
        EntityWithServiceImplAndDTO expected,
        EntityWithServiceImplAndDTO actual
    ) {
        assertEntityWithServiceImplAndDTOAutoGeneratedPropertiesEquals(expected, actual);
        assertEntityWithServiceImplAndDTOAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplAndDTOAllUpdatablePropertiesEquals(
        EntityWithServiceImplAndDTO expected,
        EntityWithServiceImplAndDTO actual
    ) {
        assertEntityWithServiceImplAndDTOUpdatableFieldsEquals(expected, actual);
        assertEntityWithServiceImplAndDTOUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplAndDTOAutoGeneratedPropertiesEquals(
        EntityWithServiceImplAndDTO expected,
        EntityWithServiceImplAndDTO actual
    ) {
        assertThat(actual)
            .as("Verify EntityWithServiceImplAndDTO auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplAndDTOUpdatableFieldsEquals(
        EntityWithServiceImplAndDTO expected,
        EntityWithServiceImplAndDTO actual
    ) {
        assertThat(actual)
            .as("Verify EntityWithServiceImplAndDTO relevant properties")
            .satisfies(a -> assertThat(a.getLouis()).as("check louis").isEqualTo(expected.getLouis()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntityWithServiceImplAndDTOUpdatableRelationshipsEquals(
        EntityWithServiceImplAndDTO expected,
        EntityWithServiceImplAndDTO actual
    ) {
        // empty method
    }
}
