package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tech.jhipster.sample.domain.AssertUtils.bigDecimalCompareTo;
import static tech.jhipster.sample.domain.AssertUtils.zonedDateTimeSameInstant;

public class FieldTestEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestEntityAllPropertiesEquals(FieldTestEntity expected, FieldTestEntity actual) {
        assertFieldTestEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertFieldTestEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestEntityAllUpdatablePropertiesEquals(FieldTestEntity expected, FieldTestEntity actual) {
        assertFieldTestEntityUpdatableFieldsEquals(expected, actual);
        assertFieldTestEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestEntityAutoGeneratedPropertiesEquals(FieldTestEntity expected, FieldTestEntity actual) {
        assertThat(actual)
            .as("Verify FieldTestEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestEntityUpdatableFieldsEquals(FieldTestEntity expected, FieldTestEntity actual) {
        assertThat(actual)
            .as("Verify FieldTestEntity relevant properties")
            .satisfies(a -> assertThat(a.getStringTom()).as("check stringTom").isEqualTo(expected.getStringTom()))
            .satisfies(a -> assertThat(a.getStringRequiredTom()).as("check stringRequiredTom").isEqualTo(expected.getStringRequiredTom()))
            .satisfies(a ->
                assertThat(a.getStringMinlengthTom()).as("check stringMinlengthTom").isEqualTo(expected.getStringMinlengthTom())
            )
            .satisfies(a ->
                assertThat(a.getStringMaxlengthTom()).as("check stringMaxlengthTom").isEqualTo(expected.getStringMaxlengthTom())
            )
            .satisfies(a -> assertThat(a.getStringPatternTom()).as("check stringPatternTom").isEqualTo(expected.getStringPatternTom()))
            .satisfies(a -> assertThat(a.getNumberPatternTom()).as("check numberPatternTom").isEqualTo(expected.getNumberPatternTom()))
            .satisfies(a ->
                assertThat(a.getNumberPatternRequiredTom())
                    .as("check numberPatternRequiredTom")
                    .isEqualTo(expected.getNumberPatternRequiredTom())
            )
            .satisfies(a -> assertThat(a.getIntegerTom()).as("check integerTom").isEqualTo(expected.getIntegerTom()))
            .satisfies(a ->
                assertThat(a.getIntegerRequiredTom()).as("check integerRequiredTom").isEqualTo(expected.getIntegerRequiredTom())
            )
            .satisfies(a -> assertThat(a.getIntegerMinTom()).as("check integerMinTom").isEqualTo(expected.getIntegerMinTom()))
            .satisfies(a -> assertThat(a.getIntegerMaxTom()).as("check integerMaxTom").isEqualTo(expected.getIntegerMaxTom()))
            .satisfies(a -> assertThat(a.getLongTom()).as("check longTom").isEqualTo(expected.getLongTom()))
            .satisfies(a -> assertThat(a.getLongRequiredTom()).as("check longRequiredTom").isEqualTo(expected.getLongRequiredTom()))
            .satisfies(a -> assertThat(a.getLongMinTom()).as("check longMinTom").isEqualTo(expected.getLongMinTom()))
            .satisfies(a -> assertThat(a.getLongMaxTom()).as("check longMaxTom").isEqualTo(expected.getLongMaxTom()))
            .satisfies(a -> assertThat(a.getFloatTom()).as("check floatTom").isEqualTo(expected.getFloatTom()))
            .satisfies(a -> assertThat(a.getFloatRequiredTom()).as("check floatRequiredTom").isEqualTo(expected.getFloatRequiredTom()))
            .satisfies(a -> assertThat(a.getFloatMinTom()).as("check floatMinTom").isEqualTo(expected.getFloatMinTom()))
            .satisfies(a -> assertThat(a.getFloatMaxTom()).as("check floatMaxTom").isEqualTo(expected.getFloatMaxTom()))
            .satisfies(a -> assertThat(a.getDoubleRequiredTom()).as("check doubleRequiredTom").isEqualTo(expected.getDoubleRequiredTom()))
            .satisfies(a -> assertThat(a.getDoubleMinTom()).as("check doubleMinTom").isEqualTo(expected.getDoubleMinTom()))
            .satisfies(a -> assertThat(a.getDoubleMaxTom()).as("check doubleMaxTom").isEqualTo(expected.getDoubleMaxTom()))
            .satisfies(a ->
                assertThat(a.getBigDecimalRequiredTom())
                    .as("check bigDecimalRequiredTom")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalRequiredTom())
            )
            .satisfies(a ->
                assertThat(a.getBigDecimalMinTom())
                    .as("check bigDecimalMinTom")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalMinTom())
            )
            .satisfies(a ->
                assertThat(a.getBigDecimalMaxTom())
                    .as("check bigDecimalMaxTom")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalMaxTom())
            )
            .satisfies(a -> assertThat(a.getLocalDateTom()).as("check localDateTom").isEqualTo(expected.getLocalDateTom()))
            .satisfies(a ->
                assertThat(a.getLocalDateRequiredTom()).as("check localDateRequiredTom").isEqualTo(expected.getLocalDateRequiredTom())
            )
            .satisfies(a -> assertThat(a.getInstantTom()).as("check instantTom").isEqualTo(expected.getInstantTom()))
            .satisfies(a ->
                assertThat(a.getInstantRequiredTom()).as("check instantRequiredTom").isEqualTo(expected.getInstantRequiredTom())
            )
            .satisfies(a ->
                assertThat(a.getZonedDateTimeTom())
                    .as("check zonedDateTimeTom")
                    .usingComparator(zonedDateTimeSameInstant)
                    .isEqualTo(expected.getZonedDateTimeTom())
            )
            .satisfies(a ->
                assertThat(a.getZonedDateTimeRequiredTom())
                    .as("check zonedDateTimeRequiredTom")
                    .usingComparator(zonedDateTimeSameInstant)
                    .isEqualTo(expected.getZonedDateTimeRequiredTom())
            )
            .satisfies(a -> assertThat(a.getLocalTimeTom()).as("check localTimeTom").isEqualTo(expected.getLocalTimeTom()))
            .satisfies(a ->
                assertThat(a.getLocalTimeRequiredTom()).as("check localTimeRequiredTom").isEqualTo(expected.getLocalTimeRequiredTom())
            )
            .satisfies(a -> assertThat(a.getDurationTom()).as("check durationTom").isEqualTo(expected.getDurationTom()))
            .satisfies(a ->
                assertThat(a.getDurationRequiredTom()).as("check durationRequiredTom").isEqualTo(expected.getDurationRequiredTom())
            )
            .satisfies(a -> assertThat(a.getBooleanTom()).as("check booleanTom").isEqualTo(expected.getBooleanTom()))
            .satisfies(a ->
                assertThat(a.getBooleanRequiredTom()).as("check booleanRequiredTom").isEqualTo(expected.getBooleanRequiredTom())
            )
            .satisfies(a -> assertThat(a.getEnumTom()).as("check enumTom").isEqualTo(expected.getEnumTom()))
            .satisfies(a -> assertThat(a.getEnumRequiredTom()).as("check enumRequiredTom").isEqualTo(expected.getEnumRequiredTom()))
            .satisfies(a -> assertThat(a.getUuidTom()).as("check uuidTom").isEqualTo(expected.getUuidTom()))
            .satisfies(a -> assertThat(a.getUuidRequiredTom()).as("check uuidRequiredTom").isEqualTo(expected.getUuidRequiredTom()))
            .satisfies(a -> assertThat(a.getByteImageTom()).as("check byteImageTom").isEqualTo(expected.getByteImageTom()))
            .satisfies(a ->
                assertThat(a.getByteImageTomContentType())
                    .as("check byteImageTom content type")
                    .isEqualTo(expected.getByteImageTomContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageRequiredTom()).as("check byteImageRequiredTom").isEqualTo(expected.getByteImageRequiredTom())
            )
            .satisfies(a ->
                assertThat(a.getByteImageRequiredTomContentType())
                    .as("check byteImageRequiredTom content type")
                    .isEqualTo(expected.getByteImageRequiredTomContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMinbytesTom()).as("check byteImageMinbytesTom").isEqualTo(expected.getByteImageMinbytesTom())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMinbytesTomContentType())
                    .as("check byteImageMinbytesTom content type")
                    .isEqualTo(expected.getByteImageMinbytesTomContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMaxbytesTom()).as("check byteImageMaxbytesTom").isEqualTo(expected.getByteImageMaxbytesTom())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMaxbytesTomContentType())
                    .as("check byteImageMaxbytesTom content type")
                    .isEqualTo(expected.getByteImageMaxbytesTomContentType())
            )
            .satisfies(a -> assertThat(a.getByteAnyTom()).as("check byteAnyTom").isEqualTo(expected.getByteAnyTom()))
            .satisfies(a ->
                assertThat(a.getByteAnyTomContentType()).as("check byteAnyTom content type").isEqualTo(expected.getByteAnyTomContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyRequiredTom()).as("check byteAnyRequiredTom").isEqualTo(expected.getByteAnyRequiredTom())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyRequiredTomContentType())
                    .as("check byteAnyRequiredTom content type")
                    .isEqualTo(expected.getByteAnyRequiredTomContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMinbytesTom()).as("check byteAnyMinbytesTom").isEqualTo(expected.getByteAnyMinbytesTom())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMinbytesTomContentType())
                    .as("check byteAnyMinbytesTom content type")
                    .isEqualTo(expected.getByteAnyMinbytesTomContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMaxbytesTom()).as("check byteAnyMaxbytesTom").isEqualTo(expected.getByteAnyMaxbytesTom())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMaxbytesTomContentType())
                    .as("check byteAnyMaxbytesTom content type")
                    .isEqualTo(expected.getByteAnyMaxbytesTomContentType())
            )
            .satisfies(a -> assertThat(a.getByteTextTom()).as("check byteTextTom").isEqualTo(expected.getByteTextTom()))
            .satisfies(a ->
                assertThat(a.getByteTextRequiredTom()).as("check byteTextRequiredTom").isEqualTo(expected.getByteTextRequiredTom())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestEntityUpdatableRelationshipsEquals(FieldTestEntity expected, FieldTestEntity actual) {
        // empty method
    }
}
