package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tech.jhipster.sample.domain.AssertUtils.bigDecimalCompareTo;
import static tech.jhipster.sample.domain.AssertUtils.zonedDateTimeSameInstant;

public class FieldTestMapstructAndServiceClassEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestMapstructAndServiceClassEntityAllPropertiesEquals(
        FieldTestMapstructAndServiceClassEntity expected,
        FieldTestMapstructAndServiceClassEntity actual
    ) {
        assertFieldTestMapstructAndServiceClassEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertFieldTestMapstructAndServiceClassEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestMapstructAndServiceClassEntityAllUpdatablePropertiesEquals(
        FieldTestMapstructAndServiceClassEntity expected,
        FieldTestMapstructAndServiceClassEntity actual
    ) {
        assertFieldTestMapstructAndServiceClassEntityUpdatableFieldsEquals(expected, actual);
        assertFieldTestMapstructAndServiceClassEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestMapstructAndServiceClassEntityAutoGeneratedPropertiesEquals(
        FieldTestMapstructAndServiceClassEntity expected,
        FieldTestMapstructAndServiceClassEntity actual
    ) {
        assertThat(actual)
            .as("Verify FieldTestMapstructAndServiceClassEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestMapstructAndServiceClassEntityUpdatableFieldsEquals(
        FieldTestMapstructAndServiceClassEntity expected,
        FieldTestMapstructAndServiceClassEntity actual
    ) {
        assertThat(actual)
            .as("Verify FieldTestMapstructAndServiceClassEntity relevant properties")
            .satisfies(a -> assertThat(a.getStringEva()).as("check stringEva").isEqualTo(expected.getStringEva()))
            .satisfies(a -> assertThat(a.getStringRequiredEva()).as("check stringRequiredEva").isEqualTo(expected.getStringRequiredEva()))
            .satisfies(a ->
                assertThat(a.getStringMinlengthEva()).as("check stringMinlengthEva").isEqualTo(expected.getStringMinlengthEva())
            )
            .satisfies(a ->
                assertThat(a.getStringMaxlengthEva()).as("check stringMaxlengthEva").isEqualTo(expected.getStringMaxlengthEva())
            )
            .satisfies(a -> assertThat(a.getStringPatternEva()).as("check stringPatternEva").isEqualTo(expected.getStringPatternEva()))
            .satisfies(a -> assertThat(a.getIntegerEva()).as("check integerEva").isEqualTo(expected.getIntegerEva()))
            .satisfies(a ->
                assertThat(a.getIntegerRequiredEva()).as("check integerRequiredEva").isEqualTo(expected.getIntegerRequiredEva())
            )
            .satisfies(a -> assertThat(a.getIntegerMinEva()).as("check integerMinEva").isEqualTo(expected.getIntegerMinEva()))
            .satisfies(a -> assertThat(a.getIntegerMaxEva()).as("check integerMaxEva").isEqualTo(expected.getIntegerMaxEva()))
            .satisfies(a -> assertThat(a.getLongEva()).as("check longEva").isEqualTo(expected.getLongEva()))
            .satisfies(a -> assertThat(a.getLongRequiredEva()).as("check longRequiredEva").isEqualTo(expected.getLongRequiredEva()))
            .satisfies(a -> assertThat(a.getLongMinEva()).as("check longMinEva").isEqualTo(expected.getLongMinEva()))
            .satisfies(a -> assertThat(a.getLongMaxEva()).as("check longMaxEva").isEqualTo(expected.getLongMaxEva()))
            .satisfies(a -> assertThat(a.getFloatEva()).as("check floatEva").isEqualTo(expected.getFloatEva()))
            .satisfies(a -> assertThat(a.getFloatRequiredEva()).as("check floatRequiredEva").isEqualTo(expected.getFloatRequiredEva()))
            .satisfies(a -> assertThat(a.getFloatMinEva()).as("check floatMinEva").isEqualTo(expected.getFloatMinEva()))
            .satisfies(a -> assertThat(a.getFloatMaxEva()).as("check floatMaxEva").isEqualTo(expected.getFloatMaxEva()))
            .satisfies(a -> assertThat(a.getDoubleRequiredEva()).as("check doubleRequiredEva").isEqualTo(expected.getDoubleRequiredEva()))
            .satisfies(a -> assertThat(a.getDoubleMinEva()).as("check doubleMinEva").isEqualTo(expected.getDoubleMinEva()))
            .satisfies(a -> assertThat(a.getDoubleMaxEva()).as("check doubleMaxEva").isEqualTo(expected.getDoubleMaxEva()))
            .satisfies(a ->
                assertThat(a.getBigDecimalRequiredEva())
                    .as("check bigDecimalRequiredEva")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalRequiredEva())
            )
            .satisfies(a ->
                assertThat(a.getBigDecimalMinEva())
                    .as("check bigDecimalMinEva")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalMinEva())
            )
            .satisfies(a ->
                assertThat(a.getBigDecimalMaxEva())
                    .as("check bigDecimalMaxEva")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalMaxEva())
            )
            .satisfies(a -> assertThat(a.getLocalDateEva()).as("check localDateEva").isEqualTo(expected.getLocalDateEva()))
            .satisfies(a ->
                assertThat(a.getLocalDateRequiredEva()).as("check localDateRequiredEva").isEqualTo(expected.getLocalDateRequiredEva())
            )
            .satisfies(a -> assertThat(a.getInstantEva()).as("check instantEva").isEqualTo(expected.getInstantEva()))
            .satisfies(a ->
                assertThat(a.getInstanteRequiredEva()).as("check instanteRequiredEva").isEqualTo(expected.getInstanteRequiredEva())
            )
            .satisfies(a ->
                assertThat(a.getZonedDateTimeEva())
                    .as("check zonedDateTimeEva")
                    .usingComparator(zonedDateTimeSameInstant)
                    .isEqualTo(expected.getZonedDateTimeEva())
            )
            .satisfies(a ->
                assertThat(a.getZonedDateTimeRequiredEva())
                    .as("check zonedDateTimeRequiredEva")
                    .usingComparator(zonedDateTimeSameInstant)
                    .isEqualTo(expected.getZonedDateTimeRequiredEva())
            )
            .satisfies(a -> assertThat(a.getLocalTimeEva()).as("check localTimeEva").isEqualTo(expected.getLocalTimeEva()))
            .satisfies(a ->
                assertThat(a.getLocalTimeRequiredEva()).as("check localTimeRequiredEva").isEqualTo(expected.getLocalTimeRequiredEva())
            )
            .satisfies(a -> assertThat(a.getDurationEva()).as("check durationEva").isEqualTo(expected.getDurationEva()))
            .satisfies(a ->
                assertThat(a.getDurationRequiredEva()).as("check durationRequiredEva").isEqualTo(expected.getDurationRequiredEva())
            )
            .satisfies(a -> assertThat(a.getBooleanEva()).as("check booleanEva").isEqualTo(expected.getBooleanEva()))
            .satisfies(a ->
                assertThat(a.getBooleanRequiredEva()).as("check booleanRequiredEva").isEqualTo(expected.getBooleanRequiredEva())
            )
            .satisfies(a -> assertThat(a.getEnumEva()).as("check enumEva").isEqualTo(expected.getEnumEva()))
            .satisfies(a -> assertThat(a.getEnumRequiredEva()).as("check enumRequiredEva").isEqualTo(expected.getEnumRequiredEva()))
            .satisfies(a -> assertThat(a.getUuidEva()).as("check uuidEva").isEqualTo(expected.getUuidEva()))
            .satisfies(a -> assertThat(a.getUuidRequiredEva()).as("check uuidRequiredEva").isEqualTo(expected.getUuidRequiredEva()))
            .satisfies(a -> assertThat(a.getByteImageEva()).as("check byteImageEva").isEqualTo(expected.getByteImageEva()))
            .satisfies(a ->
                assertThat(a.getByteImageEvaContentType())
                    .as("check byteImageEva content type")
                    .isEqualTo(expected.getByteImageEvaContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageRequiredEva()).as("check byteImageRequiredEva").isEqualTo(expected.getByteImageRequiredEva())
            )
            .satisfies(a ->
                assertThat(a.getByteImageRequiredEvaContentType())
                    .as("check byteImageRequiredEva content type")
                    .isEqualTo(expected.getByteImageRequiredEvaContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMinbytesEva()).as("check byteImageMinbytesEva").isEqualTo(expected.getByteImageMinbytesEva())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMinbytesEvaContentType())
                    .as("check byteImageMinbytesEva content type")
                    .isEqualTo(expected.getByteImageMinbytesEvaContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMaxbytesEva()).as("check byteImageMaxbytesEva").isEqualTo(expected.getByteImageMaxbytesEva())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMaxbytesEvaContentType())
                    .as("check byteImageMaxbytesEva content type")
                    .isEqualTo(expected.getByteImageMaxbytesEvaContentType())
            )
            .satisfies(a -> assertThat(a.getByteAnyEva()).as("check byteAnyEva").isEqualTo(expected.getByteAnyEva()))
            .satisfies(a ->
                assertThat(a.getByteAnyEvaContentType()).as("check byteAnyEva content type").isEqualTo(expected.getByteAnyEvaContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyRequiredEva()).as("check byteAnyRequiredEva").isEqualTo(expected.getByteAnyRequiredEva())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyRequiredEvaContentType())
                    .as("check byteAnyRequiredEva content type")
                    .isEqualTo(expected.getByteAnyRequiredEvaContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMinbytesEva()).as("check byteAnyMinbytesEva").isEqualTo(expected.getByteAnyMinbytesEva())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMinbytesEvaContentType())
                    .as("check byteAnyMinbytesEva content type")
                    .isEqualTo(expected.getByteAnyMinbytesEvaContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMaxbytesEva()).as("check byteAnyMaxbytesEva").isEqualTo(expected.getByteAnyMaxbytesEva())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMaxbytesEvaContentType())
                    .as("check byteAnyMaxbytesEva content type")
                    .isEqualTo(expected.getByteAnyMaxbytesEvaContentType())
            )
            .satisfies(a -> assertThat(a.getByteTextEva()).as("check byteTextEva").isEqualTo(expected.getByteTextEva()))
            .satisfies(a ->
                assertThat(a.getByteTextRequiredEva()).as("check byteTextRequiredEva").isEqualTo(expected.getByteTextRequiredEva())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestMapstructAndServiceClassEntityUpdatableRelationshipsEquals(
        FieldTestMapstructAndServiceClassEntity expected,
        FieldTestMapstructAndServiceClassEntity actual
    ) {
        // empty method
    }
}
