package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tech.jhipster.sample.domain.AssertUtils.bigDecimalCompareTo;
import static tech.jhipster.sample.domain.AssertUtils.zonedDateTimeSameInstant;

public class FieldTestServiceClassAndJpaFilteringEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestServiceClassAndJpaFilteringEntityAllPropertiesEquals(
        FieldTestServiceClassAndJpaFilteringEntity expected,
        FieldTestServiceClassAndJpaFilteringEntity actual
    ) {
        assertFieldTestServiceClassAndJpaFilteringEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertFieldTestServiceClassAndJpaFilteringEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestServiceClassAndJpaFilteringEntityAllUpdatablePropertiesEquals(
        FieldTestServiceClassAndJpaFilteringEntity expected,
        FieldTestServiceClassAndJpaFilteringEntity actual
    ) {
        assertFieldTestServiceClassAndJpaFilteringEntityUpdatableFieldsEquals(expected, actual);
        assertFieldTestServiceClassAndJpaFilteringEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestServiceClassAndJpaFilteringEntityAutoGeneratedPropertiesEquals(
        FieldTestServiceClassAndJpaFilteringEntity expected,
        FieldTestServiceClassAndJpaFilteringEntity actual
    ) {
        assertThat(actual)
            .as("Verify FieldTestServiceClassAndJpaFilteringEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestServiceClassAndJpaFilteringEntityUpdatableFieldsEquals(
        FieldTestServiceClassAndJpaFilteringEntity expected,
        FieldTestServiceClassAndJpaFilteringEntity actual
    ) {
        assertThat(actual)
            .as("Verify FieldTestServiceClassAndJpaFilteringEntity relevant properties")
            .satisfies(a -> assertThat(a.getStringBob()).as("check stringBob").isEqualTo(expected.getStringBob()))
            .satisfies(a -> assertThat(a.getStringRequiredBob()).as("check stringRequiredBob").isEqualTo(expected.getStringRequiredBob()))
            .satisfies(a ->
                assertThat(a.getStringMinlengthBob()).as("check stringMinlengthBob").isEqualTo(expected.getStringMinlengthBob())
            )
            .satisfies(a ->
                assertThat(a.getStringMaxlengthBob()).as("check stringMaxlengthBob").isEqualTo(expected.getStringMaxlengthBob())
            )
            .satisfies(a -> assertThat(a.getStringPatternBob()).as("check stringPatternBob").isEqualTo(expected.getStringPatternBob()))
            .satisfies(a -> assertThat(a.getIntegerBob()).as("check integerBob").isEqualTo(expected.getIntegerBob()))
            .satisfies(a ->
                assertThat(a.getIntegerRequiredBob()).as("check integerRequiredBob").isEqualTo(expected.getIntegerRequiredBob())
            )
            .satisfies(a -> assertThat(a.getIntegerMinBob()).as("check integerMinBob").isEqualTo(expected.getIntegerMinBob()))
            .satisfies(a -> assertThat(a.getIntegerMaxBob()).as("check integerMaxBob").isEqualTo(expected.getIntegerMaxBob()))
            .satisfies(a -> assertThat(a.getLongBob()).as("check longBob").isEqualTo(expected.getLongBob()))
            .satisfies(a -> assertThat(a.getLongRequiredBob()).as("check longRequiredBob").isEqualTo(expected.getLongRequiredBob()))
            .satisfies(a -> assertThat(a.getLongMinBob()).as("check longMinBob").isEqualTo(expected.getLongMinBob()))
            .satisfies(a -> assertThat(a.getLongMaxBob()).as("check longMaxBob").isEqualTo(expected.getLongMaxBob()))
            .satisfies(a -> assertThat(a.getFloatBob()).as("check floatBob").isEqualTo(expected.getFloatBob()))
            .satisfies(a -> assertThat(a.getFloatRequiredBob()).as("check floatRequiredBob").isEqualTo(expected.getFloatRequiredBob()))
            .satisfies(a -> assertThat(a.getFloatMinBob()).as("check floatMinBob").isEqualTo(expected.getFloatMinBob()))
            .satisfies(a -> assertThat(a.getFloatMaxBob()).as("check floatMaxBob").isEqualTo(expected.getFloatMaxBob()))
            .satisfies(a -> assertThat(a.getDoubleRequiredBob()).as("check doubleRequiredBob").isEqualTo(expected.getDoubleRequiredBob()))
            .satisfies(a -> assertThat(a.getDoubleMinBob()).as("check doubleMinBob").isEqualTo(expected.getDoubleMinBob()))
            .satisfies(a -> assertThat(a.getDoubleMaxBob()).as("check doubleMaxBob").isEqualTo(expected.getDoubleMaxBob()))
            .satisfies(a ->
                assertThat(a.getBigDecimalRequiredBob())
                    .as("check bigDecimalRequiredBob")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalRequiredBob())
            )
            .satisfies(a ->
                assertThat(a.getBigDecimalMinBob())
                    .as("check bigDecimalMinBob")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalMinBob())
            )
            .satisfies(a ->
                assertThat(a.getBigDecimalMaxBob())
                    .as("check bigDecimalMaxBob")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalMaxBob())
            )
            .satisfies(a -> assertThat(a.getLocalDateBob()).as("check localDateBob").isEqualTo(expected.getLocalDateBob()))
            .satisfies(a ->
                assertThat(a.getLocalDateRequiredBob()).as("check localDateRequiredBob").isEqualTo(expected.getLocalDateRequiredBob())
            )
            .satisfies(a -> assertThat(a.getInstantBob()).as("check instantBob").isEqualTo(expected.getInstantBob()))
            .satisfies(a ->
                assertThat(a.getInstanteRequiredBob()).as("check instanteRequiredBob").isEqualTo(expected.getInstanteRequiredBob())
            )
            .satisfies(a ->
                assertThat(a.getZonedDateTimeBob())
                    .as("check zonedDateTimeBob")
                    .usingComparator(zonedDateTimeSameInstant)
                    .isEqualTo(expected.getZonedDateTimeBob())
            )
            .satisfies(a ->
                assertThat(a.getZonedDateTimeRequiredBob())
                    .as("check zonedDateTimeRequiredBob")
                    .usingComparator(zonedDateTimeSameInstant)
                    .isEqualTo(expected.getZonedDateTimeRequiredBob())
            )
            .satisfies(a -> assertThat(a.getLocalTimeBob()).as("check localTimeBob").isEqualTo(expected.getLocalTimeBob()))
            .satisfies(a ->
                assertThat(a.getLocalTimeRequiredBob()).as("check localTimeRequiredBob").isEqualTo(expected.getLocalTimeRequiredBob())
            )
            .satisfies(a -> assertThat(a.getDurationBob()).as("check durationBob").isEqualTo(expected.getDurationBob()))
            .satisfies(a ->
                assertThat(a.getDurationRequiredBob()).as("check durationRequiredBob").isEqualTo(expected.getDurationRequiredBob())
            )
            .satisfies(a -> assertThat(a.getBooleanBob()).as("check booleanBob").isEqualTo(expected.getBooleanBob()))
            .satisfies(a ->
                assertThat(a.getBooleanRequiredBob()).as("check booleanRequiredBob").isEqualTo(expected.getBooleanRequiredBob())
            )
            .satisfies(a -> assertThat(a.getEnumBob()).as("check enumBob").isEqualTo(expected.getEnumBob()))
            .satisfies(a -> assertThat(a.getEnumRequiredBob()).as("check enumRequiredBob").isEqualTo(expected.getEnumRequiredBob()))
            .satisfies(a -> assertThat(a.getUuidBob()).as("check uuidBob").isEqualTo(expected.getUuidBob()))
            .satisfies(a -> assertThat(a.getUuidRequiredBob()).as("check uuidRequiredBob").isEqualTo(expected.getUuidRequiredBob()))
            .satisfies(a -> assertThat(a.getByteImageBob()).as("check byteImageBob").isEqualTo(expected.getByteImageBob()))
            .satisfies(a ->
                assertThat(a.getByteImageBobContentType())
                    .as("check byteImageBob content type")
                    .isEqualTo(expected.getByteImageBobContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageRequiredBob()).as("check byteImageRequiredBob").isEqualTo(expected.getByteImageRequiredBob())
            )
            .satisfies(a ->
                assertThat(a.getByteImageRequiredBobContentType())
                    .as("check byteImageRequiredBob content type")
                    .isEqualTo(expected.getByteImageRequiredBobContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMinbytesBob()).as("check byteImageMinbytesBob").isEqualTo(expected.getByteImageMinbytesBob())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMinbytesBobContentType())
                    .as("check byteImageMinbytesBob content type")
                    .isEqualTo(expected.getByteImageMinbytesBobContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMaxbytesBob()).as("check byteImageMaxbytesBob").isEqualTo(expected.getByteImageMaxbytesBob())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMaxbytesBobContentType())
                    .as("check byteImageMaxbytesBob content type")
                    .isEqualTo(expected.getByteImageMaxbytesBobContentType())
            )
            .satisfies(a -> assertThat(a.getByteAnyBob()).as("check byteAnyBob").isEqualTo(expected.getByteAnyBob()))
            .satisfies(a ->
                assertThat(a.getByteAnyBobContentType()).as("check byteAnyBob content type").isEqualTo(expected.getByteAnyBobContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyRequiredBob()).as("check byteAnyRequiredBob").isEqualTo(expected.getByteAnyRequiredBob())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyRequiredBobContentType())
                    .as("check byteAnyRequiredBob content type")
                    .isEqualTo(expected.getByteAnyRequiredBobContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMinbytesBob()).as("check byteAnyMinbytesBob").isEqualTo(expected.getByteAnyMinbytesBob())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMinbytesBobContentType())
                    .as("check byteAnyMinbytesBob content type")
                    .isEqualTo(expected.getByteAnyMinbytesBobContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMaxbytesBob()).as("check byteAnyMaxbytesBob").isEqualTo(expected.getByteAnyMaxbytesBob())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMaxbytesBobContentType())
                    .as("check byteAnyMaxbytesBob content type")
                    .isEqualTo(expected.getByteAnyMaxbytesBobContentType())
            )
            .satisfies(a -> assertThat(a.getByteTextBob()).as("check byteTextBob").isEqualTo(expected.getByteTextBob()))
            .satisfies(a ->
                assertThat(a.getByteTextRequiredBob()).as("check byteTextRequiredBob").isEqualTo(expected.getByteTextRequiredBob())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestServiceClassAndJpaFilteringEntityUpdatableRelationshipsEquals(
        FieldTestServiceClassAndJpaFilteringEntity expected,
        FieldTestServiceClassAndJpaFilteringEntity actual
    ) {
        // empty method
    }
}
