package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tech.jhipster.sample.domain.AssertUtils.bigDecimalCompareTo;
import static tech.jhipster.sample.domain.AssertUtils.zonedDateTimeSameInstant;

public class FieldTestInfiniteScrollEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestInfiniteScrollEntityAllPropertiesEquals(
        FieldTestInfiniteScrollEntity expected,
        FieldTestInfiniteScrollEntity actual
    ) {
        assertFieldTestInfiniteScrollEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertFieldTestInfiniteScrollEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestInfiniteScrollEntityAllUpdatablePropertiesEquals(
        FieldTestInfiniteScrollEntity expected,
        FieldTestInfiniteScrollEntity actual
    ) {
        assertFieldTestInfiniteScrollEntityUpdatableFieldsEquals(expected, actual);
        assertFieldTestInfiniteScrollEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestInfiniteScrollEntityAutoGeneratedPropertiesEquals(
        FieldTestInfiniteScrollEntity expected,
        FieldTestInfiniteScrollEntity actual
    ) {
        assertThat(actual)
            .as("Verify FieldTestInfiniteScrollEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestInfiniteScrollEntityUpdatableFieldsEquals(
        FieldTestInfiniteScrollEntity expected,
        FieldTestInfiniteScrollEntity actual
    ) {
        assertThat(actual)
            .as("Verify FieldTestInfiniteScrollEntity relevant properties")
            .satisfies(a -> assertThat(a.getStringHugo()).as("check stringHugo").isEqualTo(expected.getStringHugo()))
            .satisfies(a ->
                assertThat(a.getStringRequiredHugo()).as("check stringRequiredHugo").isEqualTo(expected.getStringRequiredHugo())
            )
            .satisfies(a ->
                assertThat(a.getStringMinlengthHugo()).as("check stringMinlengthHugo").isEqualTo(expected.getStringMinlengthHugo())
            )
            .satisfies(a ->
                assertThat(a.getStringMaxlengthHugo()).as("check stringMaxlengthHugo").isEqualTo(expected.getStringMaxlengthHugo())
            )
            .satisfies(a -> assertThat(a.getStringPatternHugo()).as("check stringPatternHugo").isEqualTo(expected.getStringPatternHugo()))
            .satisfies(a -> assertThat(a.getIntegerHugo()).as("check integerHugo").isEqualTo(expected.getIntegerHugo()))
            .satisfies(a ->
                assertThat(a.getIntegerRequiredHugo()).as("check integerRequiredHugo").isEqualTo(expected.getIntegerRequiredHugo())
            )
            .satisfies(a -> assertThat(a.getIntegerMinHugo()).as("check integerMinHugo").isEqualTo(expected.getIntegerMinHugo()))
            .satisfies(a -> assertThat(a.getIntegerMaxHugo()).as("check integerMaxHugo").isEqualTo(expected.getIntegerMaxHugo()))
            .satisfies(a -> assertThat(a.getLongHugo()).as("check longHugo").isEqualTo(expected.getLongHugo()))
            .satisfies(a -> assertThat(a.getLongRequiredHugo()).as("check longRequiredHugo").isEqualTo(expected.getLongRequiredHugo()))
            .satisfies(a -> assertThat(a.getLongMinHugo()).as("check longMinHugo").isEqualTo(expected.getLongMinHugo()))
            .satisfies(a -> assertThat(a.getLongMaxHugo()).as("check longMaxHugo").isEqualTo(expected.getLongMaxHugo()))
            .satisfies(a -> assertThat(a.getFloatHugo()).as("check floatHugo").isEqualTo(expected.getFloatHugo()))
            .satisfies(a -> assertThat(a.getFloatRequiredHugo()).as("check floatRequiredHugo").isEqualTo(expected.getFloatRequiredHugo()))
            .satisfies(a -> assertThat(a.getFloatMinHugo()).as("check floatMinHugo").isEqualTo(expected.getFloatMinHugo()))
            .satisfies(a -> assertThat(a.getFloatMaxHugo()).as("check floatMaxHugo").isEqualTo(expected.getFloatMaxHugo()))
            .satisfies(a ->
                assertThat(a.getDoubleRequiredHugo()).as("check doubleRequiredHugo").isEqualTo(expected.getDoubleRequiredHugo())
            )
            .satisfies(a -> assertThat(a.getDoubleMinHugo()).as("check doubleMinHugo").isEqualTo(expected.getDoubleMinHugo()))
            .satisfies(a -> assertThat(a.getDoubleMaxHugo()).as("check doubleMaxHugo").isEqualTo(expected.getDoubleMaxHugo()))
            .satisfies(a ->
                assertThat(a.getBigDecimalRequiredHugo())
                    .as("check bigDecimalRequiredHugo")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalRequiredHugo())
            )
            .satisfies(a ->
                assertThat(a.getBigDecimalMinHugo())
                    .as("check bigDecimalMinHugo")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalMinHugo())
            )
            .satisfies(a ->
                assertThat(a.getBigDecimalMaxHugo())
                    .as("check bigDecimalMaxHugo")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalMaxHugo())
            )
            .satisfies(a -> assertThat(a.getLocalDateHugo()).as("check localDateHugo").isEqualTo(expected.getLocalDateHugo()))
            .satisfies(a ->
                assertThat(a.getLocalDateRequiredHugo()).as("check localDateRequiredHugo").isEqualTo(expected.getLocalDateRequiredHugo())
            )
            .satisfies(a -> assertThat(a.getInstantHugo()).as("check instantHugo").isEqualTo(expected.getInstantHugo()))
            .satisfies(a ->
                assertThat(a.getInstanteRequiredHugo()).as("check instanteRequiredHugo").isEqualTo(expected.getInstanteRequiredHugo())
            )
            .satisfies(a ->
                assertThat(a.getZonedDateTimeHugo())
                    .as("check zonedDateTimeHugo")
                    .usingComparator(zonedDateTimeSameInstant)
                    .isEqualTo(expected.getZonedDateTimeHugo())
            )
            .satisfies(a ->
                assertThat(a.getZonedDateTimeRequiredHugo())
                    .as("check zonedDateTimeRequiredHugo")
                    .usingComparator(zonedDateTimeSameInstant)
                    .isEqualTo(expected.getZonedDateTimeRequiredHugo())
            )
            .satisfies(a -> assertThat(a.getLocalTimeHugo()).as("check localTimeHugo").isEqualTo(expected.getLocalTimeHugo()))
            .satisfies(a ->
                assertThat(a.getLocalTimeRequiredHugo()).as("check localTimeRequiredHugo").isEqualTo(expected.getLocalTimeRequiredHugo())
            )
            .satisfies(a -> assertThat(a.getDurationHugo()).as("check durationHugo").isEqualTo(expected.getDurationHugo()))
            .satisfies(a ->
                assertThat(a.getDurationRequiredHugo()).as("check durationRequiredHugo").isEqualTo(expected.getDurationRequiredHugo())
            )
            .satisfies(a -> assertThat(a.getBooleanHugo()).as("check booleanHugo").isEqualTo(expected.getBooleanHugo()))
            .satisfies(a ->
                assertThat(a.getBooleanRequiredHugo()).as("check booleanRequiredHugo").isEqualTo(expected.getBooleanRequiredHugo())
            )
            .satisfies(a -> assertThat(a.getEnumHugo()).as("check enumHugo").isEqualTo(expected.getEnumHugo()))
            .satisfies(a -> assertThat(a.getEnumRequiredHugo()).as("check enumRequiredHugo").isEqualTo(expected.getEnumRequiredHugo()))
            .satisfies(a -> assertThat(a.getUuidHugo()).as("check uuidHugo").isEqualTo(expected.getUuidHugo()))
            .satisfies(a -> assertThat(a.getUuidRequiredHugo()).as("check uuidRequiredHugo").isEqualTo(expected.getUuidRequiredHugo()))
            .satisfies(a -> assertThat(a.getByteImageHugo()).as("check byteImageHugo").isEqualTo(expected.getByteImageHugo()))
            .satisfies(a ->
                assertThat(a.getByteImageHugoContentType())
                    .as("check byteImageHugo content type")
                    .isEqualTo(expected.getByteImageHugoContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageRequiredHugo()).as("check byteImageRequiredHugo").isEqualTo(expected.getByteImageRequiredHugo())
            )
            .satisfies(a ->
                assertThat(a.getByteImageRequiredHugoContentType())
                    .as("check byteImageRequiredHugo content type")
                    .isEqualTo(expected.getByteImageRequiredHugoContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMinbytesHugo()).as("check byteImageMinbytesHugo").isEqualTo(expected.getByteImageMinbytesHugo())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMinbytesHugoContentType())
                    .as("check byteImageMinbytesHugo content type")
                    .isEqualTo(expected.getByteImageMinbytesHugoContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMaxbytesHugo()).as("check byteImageMaxbytesHugo").isEqualTo(expected.getByteImageMaxbytesHugo())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMaxbytesHugoContentType())
                    .as("check byteImageMaxbytesHugo content type")
                    .isEqualTo(expected.getByteImageMaxbytesHugoContentType())
            )
            .satisfies(a -> assertThat(a.getByteAnyHugo()).as("check byteAnyHugo").isEqualTo(expected.getByteAnyHugo()))
            .satisfies(a ->
                assertThat(a.getByteAnyHugoContentType())
                    .as("check byteAnyHugo content type")
                    .isEqualTo(expected.getByteAnyHugoContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyRequiredHugo()).as("check byteAnyRequiredHugo").isEqualTo(expected.getByteAnyRequiredHugo())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyRequiredHugoContentType())
                    .as("check byteAnyRequiredHugo content type")
                    .isEqualTo(expected.getByteAnyRequiredHugoContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMinbytesHugo()).as("check byteAnyMinbytesHugo").isEqualTo(expected.getByteAnyMinbytesHugo())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMinbytesHugoContentType())
                    .as("check byteAnyMinbytesHugo content type")
                    .isEqualTo(expected.getByteAnyMinbytesHugoContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMaxbytesHugo()).as("check byteAnyMaxbytesHugo").isEqualTo(expected.getByteAnyMaxbytesHugo())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMaxbytesHugoContentType())
                    .as("check byteAnyMaxbytesHugo content type")
                    .isEqualTo(expected.getByteAnyMaxbytesHugoContentType())
            )
            .satisfies(a -> assertThat(a.getByteTextHugo()).as("check byteTextHugo").isEqualTo(expected.getByteTextHugo()))
            .satisfies(a ->
                assertThat(a.getByteTextRequiredHugo()).as("check byteTextRequiredHugo").isEqualTo(expected.getByteTextRequiredHugo())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestInfiniteScrollEntityUpdatableRelationshipsEquals(
        FieldTestInfiniteScrollEntity expected,
        FieldTestInfiniteScrollEntity actual
    ) {
        // empty method
    }
}
