package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FieldTestEnumWithValueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestEnumWithValueAllPropertiesEquals(FieldTestEnumWithValue expected, FieldTestEnumWithValue actual) {
        assertFieldTestEnumWithValueAutoGeneratedPropertiesEquals(expected, actual);
        assertFieldTestEnumWithValueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestEnumWithValueAllUpdatablePropertiesEquals(
        FieldTestEnumWithValue expected,
        FieldTestEnumWithValue actual
    ) {
        assertFieldTestEnumWithValueUpdatableFieldsEquals(expected, actual);
        assertFieldTestEnumWithValueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestEnumWithValueAutoGeneratedPropertiesEquals(
        FieldTestEnumWithValue expected,
        FieldTestEnumWithValue actual
    ) {
        assertThat(actual)
            .as("Verify FieldTestEnumWithValue auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestEnumWithValueUpdatableFieldsEquals(FieldTestEnumWithValue expected, FieldTestEnumWithValue actual) {
        assertThat(actual)
            .as("Verify FieldTestEnumWithValue relevant properties")
            .satisfies(a -> assertThat(a.getMyFieldA()).as("check myFieldA").isEqualTo(expected.getMyFieldA()))
            .satisfies(a -> assertThat(a.getMyFieldB()).as("check myFieldB").isEqualTo(expected.getMyFieldB()))
            .satisfies(a -> assertThat(a.getMyFieldC()).as("check myFieldC").isEqualTo(expected.getMyFieldC()))
            .satisfies(a -> assertThat(a.getMyFieldD()).as("check myFieldD").isEqualTo(expected.getMyFieldD()))
            .satisfies(a -> assertThat(a.getMyFieldE()).as("check myFieldE").isEqualTo(expected.getMyFieldE()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestEnumWithValueUpdatableRelationshipsEquals(
        FieldTestEnumWithValue expected,
        FieldTestEnumWithValue actual
    ) {
        // empty method
    }
}
