package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tech.jhipster.sample.domain.AssertUtils.bigDecimalCompareTo;
import static tech.jhipster.sample.domain.AssertUtils.zonedDateTimeSameInstant;

public class FieldTestPaginationEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestPaginationEntityAllPropertiesEquals(
        FieldTestPaginationEntity expected,
        FieldTestPaginationEntity actual
    ) {
        assertFieldTestPaginationEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertFieldTestPaginationEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestPaginationEntityAllUpdatablePropertiesEquals(
        FieldTestPaginationEntity expected,
        FieldTestPaginationEntity actual
    ) {
        assertFieldTestPaginationEntityUpdatableFieldsEquals(expected, actual);
        assertFieldTestPaginationEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestPaginationEntityAutoGeneratedPropertiesEquals(
        FieldTestPaginationEntity expected,
        FieldTestPaginationEntity actual
    ) {
        assertThat(actual)
            .as("Verify FieldTestPaginationEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestPaginationEntityUpdatableFieldsEquals(
        FieldTestPaginationEntity expected,
        FieldTestPaginationEntity actual
    ) {
        assertThat(actual)
            .as("Verify FieldTestPaginationEntity relevant properties")
            .satisfies(a -> assertThat(a.getStringAlice()).as("check stringAlice").isEqualTo(expected.getStringAlice()))
            .satisfies(a ->
                assertThat(a.getStringRequiredAlice()).as("check stringRequiredAlice").isEqualTo(expected.getStringRequiredAlice())
            )
            .satisfies(a ->
                assertThat(a.getStringMinlengthAlice()).as("check stringMinlengthAlice").isEqualTo(expected.getStringMinlengthAlice())
            )
            .satisfies(a ->
                assertThat(a.getStringMaxlengthAlice()).as("check stringMaxlengthAlice").isEqualTo(expected.getStringMaxlengthAlice())
            )
            .satisfies(a ->
                assertThat(a.getStringPatternAlice()).as("check stringPatternAlice").isEqualTo(expected.getStringPatternAlice())
            )
            .satisfies(a -> assertThat(a.getIntegerAlice()).as("check integerAlice").isEqualTo(expected.getIntegerAlice()))
            .satisfies(a ->
                assertThat(a.getIntegerRequiredAlice()).as("check integerRequiredAlice").isEqualTo(expected.getIntegerRequiredAlice())
            )
            .satisfies(a -> assertThat(a.getIntegerMinAlice()).as("check integerMinAlice").isEqualTo(expected.getIntegerMinAlice()))
            .satisfies(a -> assertThat(a.getIntegerMaxAlice()).as("check integerMaxAlice").isEqualTo(expected.getIntegerMaxAlice()))
            .satisfies(a -> assertThat(a.getLongAlice()).as("check longAlice").isEqualTo(expected.getLongAlice()))
            .satisfies(a -> assertThat(a.getLongRequiredAlice()).as("check longRequiredAlice").isEqualTo(expected.getLongRequiredAlice()))
            .satisfies(a -> assertThat(a.getLongMinAlice()).as("check longMinAlice").isEqualTo(expected.getLongMinAlice()))
            .satisfies(a -> assertThat(a.getLongMaxAlice()).as("check longMaxAlice").isEqualTo(expected.getLongMaxAlice()))
            .satisfies(a -> assertThat(a.getFloatAlice()).as("check floatAlice").isEqualTo(expected.getFloatAlice()))
            .satisfies(a ->
                assertThat(a.getFloatRequiredAlice()).as("check floatRequiredAlice").isEqualTo(expected.getFloatRequiredAlice())
            )
            .satisfies(a -> assertThat(a.getFloatMinAlice()).as("check floatMinAlice").isEqualTo(expected.getFloatMinAlice()))
            .satisfies(a -> assertThat(a.getFloatMaxAlice()).as("check floatMaxAlice").isEqualTo(expected.getFloatMaxAlice()))
            .satisfies(a ->
                assertThat(a.getDoubleRequiredAlice()).as("check doubleRequiredAlice").isEqualTo(expected.getDoubleRequiredAlice())
            )
            .satisfies(a -> assertThat(a.getDoubleMinAlice()).as("check doubleMinAlice").isEqualTo(expected.getDoubleMinAlice()))
            .satisfies(a -> assertThat(a.getDoubleMaxAlice()).as("check doubleMaxAlice").isEqualTo(expected.getDoubleMaxAlice()))
            .satisfies(a ->
                assertThat(a.getBigDecimalRequiredAlice())
                    .as("check bigDecimalRequiredAlice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalRequiredAlice())
            )
            .satisfies(a ->
                assertThat(a.getBigDecimalMinAlice())
                    .as("check bigDecimalMinAlice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalMinAlice())
            )
            .satisfies(a ->
                assertThat(a.getBigDecimalMaxAlice())
                    .as("check bigDecimalMaxAlice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalMaxAlice())
            )
            .satisfies(a -> assertThat(a.getLocalDateAlice()).as("check localDateAlice").isEqualTo(expected.getLocalDateAlice()))
            .satisfies(a ->
                assertThat(a.getLocalDateRequiredAlice()).as("check localDateRequiredAlice").isEqualTo(expected.getLocalDateRequiredAlice())
            )
            .satisfies(a -> assertThat(a.getInstantAlice()).as("check instantAlice").isEqualTo(expected.getInstantAlice()))
            .satisfies(a ->
                assertThat(a.getInstanteRequiredAlice()).as("check instanteRequiredAlice").isEqualTo(expected.getInstanteRequiredAlice())
            )
            .satisfies(a ->
                assertThat(a.getZonedDateTimeAlice())
                    .as("check zonedDateTimeAlice")
                    .usingComparator(zonedDateTimeSameInstant)
                    .isEqualTo(expected.getZonedDateTimeAlice())
            )
            .satisfies(a ->
                assertThat(a.getZonedDateTimeRequiredAlice())
                    .as("check zonedDateTimeRequiredAlice")
                    .usingComparator(zonedDateTimeSameInstant)
                    .isEqualTo(expected.getZonedDateTimeRequiredAlice())
            )
            .satisfies(a -> assertThat(a.getLocalTimeAlice()).as("check localTimeAlice").isEqualTo(expected.getLocalTimeAlice()))
            .satisfies(a ->
                assertThat(a.getLocalTimeRequiredAlice()).as("check localTimeRequiredAlice").isEqualTo(expected.getLocalTimeRequiredAlice())
            )
            .satisfies(a -> assertThat(a.getDurationAlice()).as("check durationAlice").isEqualTo(expected.getDurationAlice()))
            .satisfies(a ->
                assertThat(a.getDurationRequiredAlice()).as("check durationRequiredAlice").isEqualTo(expected.getDurationRequiredAlice())
            )
            .satisfies(a -> assertThat(a.getBooleanAlice()).as("check booleanAlice").isEqualTo(expected.getBooleanAlice()))
            .satisfies(a ->
                assertThat(a.getBooleanRequiredAlice()).as("check booleanRequiredAlice").isEqualTo(expected.getBooleanRequiredAlice())
            )
            .satisfies(a -> assertThat(a.getEnumAlice()).as("check enumAlice").isEqualTo(expected.getEnumAlice()))
            .satisfies(a -> assertThat(a.getEnumRequiredAlice()).as("check enumRequiredAlice").isEqualTo(expected.getEnumRequiredAlice()))
            .satisfies(a -> assertThat(a.getUuidAlice()).as("check uuidAlice").isEqualTo(expected.getUuidAlice()))
            .satisfies(a -> assertThat(a.getUuidRequiredAlice()).as("check uuidRequiredAlice").isEqualTo(expected.getUuidRequiredAlice()))
            .satisfies(a -> assertThat(a.getByteImageAlice()).as("check byteImageAlice").isEqualTo(expected.getByteImageAlice()))
            .satisfies(a ->
                assertThat(a.getByteImageAliceContentType())
                    .as("check byteImageAlice content type")
                    .isEqualTo(expected.getByteImageAliceContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageRequiredAlice()).as("check byteImageRequiredAlice").isEqualTo(expected.getByteImageRequiredAlice())
            )
            .satisfies(a ->
                assertThat(a.getByteImageRequiredAliceContentType())
                    .as("check byteImageRequiredAlice content type")
                    .isEqualTo(expected.getByteImageRequiredAliceContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMinbytesAlice()).as("check byteImageMinbytesAlice").isEqualTo(expected.getByteImageMinbytesAlice())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMinbytesAliceContentType())
                    .as("check byteImageMinbytesAlice content type")
                    .isEqualTo(expected.getByteImageMinbytesAliceContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMaxbytesAlice()).as("check byteImageMaxbytesAlice").isEqualTo(expected.getByteImageMaxbytesAlice())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMaxbytesAliceContentType())
                    .as("check byteImageMaxbytesAlice content type")
                    .isEqualTo(expected.getByteImageMaxbytesAliceContentType())
            )
            .satisfies(a -> assertThat(a.getByteAnyAlice()).as("check byteAnyAlice").isEqualTo(expected.getByteAnyAlice()))
            .satisfies(a ->
                assertThat(a.getByteAnyAliceContentType())
                    .as("check byteAnyAlice content type")
                    .isEqualTo(expected.getByteAnyAliceContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyRequiredAlice()).as("check byteAnyRequiredAlice").isEqualTo(expected.getByteAnyRequiredAlice())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyRequiredAliceContentType())
                    .as("check byteAnyRequiredAlice content type")
                    .isEqualTo(expected.getByteAnyRequiredAliceContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMinbytesAlice()).as("check byteAnyMinbytesAlice").isEqualTo(expected.getByteAnyMinbytesAlice())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMinbytesAliceContentType())
                    .as("check byteAnyMinbytesAlice content type")
                    .isEqualTo(expected.getByteAnyMinbytesAliceContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMaxbytesAlice()).as("check byteAnyMaxbytesAlice").isEqualTo(expected.getByteAnyMaxbytesAlice())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMaxbytesAliceContentType())
                    .as("check byteAnyMaxbytesAlice content type")
                    .isEqualTo(expected.getByteAnyMaxbytesAliceContentType())
            )
            .satisfies(a -> assertThat(a.getByteTextAlice()).as("check byteTextAlice").isEqualTo(expected.getByteTextAlice()))
            .satisfies(a ->
                assertThat(a.getByteTextRequiredAlice()).as("check byteTextRequiredAlice").isEqualTo(expected.getByteTextRequiredAlice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestPaginationEntityUpdatableRelationshipsEquals(
        FieldTestPaginationEntity expected,
        FieldTestPaginationEntity actual
    ) {
        // empty method
    }
}
