package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static tech.jhipster.sample.domain.AssertUtils.bigDecimalCompareTo;
import static tech.jhipster.sample.domain.AssertUtils.zonedDateTimeSameInstant;

public class FieldTestServiceImplEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestServiceImplEntityAllPropertiesEquals(
        FieldTestServiceImplEntity expected,
        FieldTestServiceImplEntity actual
    ) {
        assertFieldTestServiceImplEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertFieldTestServiceImplEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestServiceImplEntityAllUpdatablePropertiesEquals(
        FieldTestServiceImplEntity expected,
        FieldTestServiceImplEntity actual
    ) {
        assertFieldTestServiceImplEntityUpdatableFieldsEquals(expected, actual);
        assertFieldTestServiceImplEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestServiceImplEntityAutoGeneratedPropertiesEquals(
        FieldTestServiceImplEntity expected,
        FieldTestServiceImplEntity actual
    ) {
        assertThat(actual)
            .as("Verify FieldTestServiceImplEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestServiceImplEntityUpdatableFieldsEquals(
        FieldTestServiceImplEntity expected,
        FieldTestServiceImplEntity actual
    ) {
        assertThat(actual)
            .as("Verify FieldTestServiceImplEntity relevant properties")
            .satisfies(a -> assertThat(a.getStringMika()).as("check stringMika").isEqualTo(expected.getStringMika()))
            .satisfies(a ->
                assertThat(a.getStringRequiredMika()).as("check stringRequiredMika").isEqualTo(expected.getStringRequiredMika())
            )
            .satisfies(a ->
                assertThat(a.getStringMinlengthMika()).as("check stringMinlengthMika").isEqualTo(expected.getStringMinlengthMika())
            )
            .satisfies(a ->
                assertThat(a.getStringMaxlengthMika()).as("check stringMaxlengthMika").isEqualTo(expected.getStringMaxlengthMika())
            )
            .satisfies(a -> assertThat(a.getStringPatternMika()).as("check stringPatternMika").isEqualTo(expected.getStringPatternMika()))
            .satisfies(a -> assertThat(a.getIntegerMika()).as("check integerMika").isEqualTo(expected.getIntegerMika()))
            .satisfies(a ->
                assertThat(a.getIntegerRequiredMika()).as("check integerRequiredMika").isEqualTo(expected.getIntegerRequiredMika())
            )
            .satisfies(a -> assertThat(a.getIntegerMinMika()).as("check integerMinMika").isEqualTo(expected.getIntegerMinMika()))
            .satisfies(a -> assertThat(a.getIntegerMaxMika()).as("check integerMaxMika").isEqualTo(expected.getIntegerMaxMika()))
            .satisfies(a -> assertThat(a.getLongMika()).as("check longMika").isEqualTo(expected.getLongMika()))
            .satisfies(a -> assertThat(a.getLongRequiredMika()).as("check longRequiredMika").isEqualTo(expected.getLongRequiredMika()))
            .satisfies(a -> assertThat(a.getLongMinMika()).as("check longMinMika").isEqualTo(expected.getLongMinMika()))
            .satisfies(a -> assertThat(a.getLongMaxMika()).as("check longMaxMika").isEqualTo(expected.getLongMaxMika()))
            .satisfies(a -> assertThat(a.getFloatMika()).as("check floatMika").isEqualTo(expected.getFloatMika()))
            .satisfies(a -> assertThat(a.getFloatRequiredMika()).as("check floatRequiredMika").isEqualTo(expected.getFloatRequiredMika()))
            .satisfies(a -> assertThat(a.getFloatMinMika()).as("check floatMinMika").isEqualTo(expected.getFloatMinMika()))
            .satisfies(a -> assertThat(a.getFloatMaxMika()).as("check floatMaxMika").isEqualTo(expected.getFloatMaxMika()))
            .satisfies(a ->
                assertThat(a.getDoubleRequiredMika()).as("check doubleRequiredMika").isEqualTo(expected.getDoubleRequiredMika())
            )
            .satisfies(a -> assertThat(a.getDoubleMinMika()).as("check doubleMinMika").isEqualTo(expected.getDoubleMinMika()))
            .satisfies(a -> assertThat(a.getDoubleMaxMika()).as("check doubleMaxMika").isEqualTo(expected.getDoubleMaxMika()))
            .satisfies(a ->
                assertThat(a.getBigDecimalRequiredMika())
                    .as("check bigDecimalRequiredMika")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalRequiredMika())
            )
            .satisfies(a ->
                assertThat(a.getBigDecimalMinMika())
                    .as("check bigDecimalMinMika")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalMinMika())
            )
            .satisfies(a ->
                assertThat(a.getBigDecimalMaxMika())
                    .as("check bigDecimalMaxMika")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBigDecimalMaxMika())
            )
            .satisfies(a -> assertThat(a.getLocalDateMika()).as("check localDateMika").isEqualTo(expected.getLocalDateMika()))
            .satisfies(a ->
                assertThat(a.getLocalDateRequiredMika()).as("check localDateRequiredMika").isEqualTo(expected.getLocalDateRequiredMika())
            )
            .satisfies(a -> assertThat(a.getInstantMika()).as("check instantMika").isEqualTo(expected.getInstantMika()))
            .satisfies(a ->
                assertThat(a.getInstanteRequiredMika()).as("check instanteRequiredMika").isEqualTo(expected.getInstanteRequiredMika())
            )
            .satisfies(a ->
                assertThat(a.getZonedDateTimeMika())
                    .as("check zonedDateTimeMika")
                    .usingComparator(zonedDateTimeSameInstant)
                    .isEqualTo(expected.getZonedDateTimeMika())
            )
            .satisfies(a ->
                assertThat(a.getZonedDateTimeRequiredMika())
                    .as("check zonedDateTimeRequiredMika")
                    .usingComparator(zonedDateTimeSameInstant)
                    .isEqualTo(expected.getZonedDateTimeRequiredMika())
            )
            .satisfies(a -> assertThat(a.getLocalTimeMika()).as("check localTimeMika").isEqualTo(expected.getLocalTimeMika()))
            .satisfies(a ->
                assertThat(a.getLocalTimeRequiredMika()).as("check localTimeRequiredMika").isEqualTo(expected.getLocalTimeRequiredMika())
            )
            .satisfies(a -> assertThat(a.getDurationMika()).as("check durationMika").isEqualTo(expected.getDurationMika()))
            .satisfies(a ->
                assertThat(a.getDurationRequiredMika()).as("check durationRequiredMika").isEqualTo(expected.getDurationRequiredMika())
            )
            .satisfies(a -> assertThat(a.getBooleanMika()).as("check booleanMika").isEqualTo(expected.getBooleanMika()))
            .satisfies(a ->
                assertThat(a.getBooleanRequiredMika()).as("check booleanRequiredMika").isEqualTo(expected.getBooleanRequiredMika())
            )
            .satisfies(a -> assertThat(a.getEnumMika()).as("check enumMika").isEqualTo(expected.getEnumMika()))
            .satisfies(a -> assertThat(a.getEnumRequiredMika()).as("check enumRequiredMika").isEqualTo(expected.getEnumRequiredMika()))
            .satisfies(a -> assertThat(a.getUuidMika()).as("check uuidMika").isEqualTo(expected.getUuidMika()))
            .satisfies(a -> assertThat(a.getUuidRequiredMika()).as("check uuidRequiredMika").isEqualTo(expected.getUuidRequiredMika()))
            .satisfies(a -> assertThat(a.getByteImageMika()).as("check byteImageMika").isEqualTo(expected.getByteImageMika()))
            .satisfies(a ->
                assertThat(a.getByteImageMikaContentType())
                    .as("check byteImageMika content type")
                    .isEqualTo(expected.getByteImageMikaContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageRequiredMika()).as("check byteImageRequiredMika").isEqualTo(expected.getByteImageRequiredMika())
            )
            .satisfies(a ->
                assertThat(a.getByteImageRequiredMikaContentType())
                    .as("check byteImageRequiredMika content type")
                    .isEqualTo(expected.getByteImageRequiredMikaContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMinbytesMika()).as("check byteImageMinbytesMika").isEqualTo(expected.getByteImageMinbytesMika())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMinbytesMikaContentType())
                    .as("check byteImageMinbytesMika content type")
                    .isEqualTo(expected.getByteImageMinbytesMikaContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMaxbytesMika()).as("check byteImageMaxbytesMika").isEqualTo(expected.getByteImageMaxbytesMika())
            )
            .satisfies(a ->
                assertThat(a.getByteImageMaxbytesMikaContentType())
                    .as("check byteImageMaxbytesMika content type")
                    .isEqualTo(expected.getByteImageMaxbytesMikaContentType())
            )
            .satisfies(a -> assertThat(a.getByteAnyMika()).as("check byteAnyMika").isEqualTo(expected.getByteAnyMika()))
            .satisfies(a ->
                assertThat(a.getByteAnyMikaContentType())
                    .as("check byteAnyMika content type")
                    .isEqualTo(expected.getByteAnyMikaContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyRequiredMika()).as("check byteAnyRequiredMika").isEqualTo(expected.getByteAnyRequiredMika())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyRequiredMikaContentType())
                    .as("check byteAnyRequiredMika content type")
                    .isEqualTo(expected.getByteAnyRequiredMikaContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMinbytesMika()).as("check byteAnyMinbytesMika").isEqualTo(expected.getByteAnyMinbytesMika())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMinbytesMikaContentType())
                    .as("check byteAnyMinbytesMika content type")
                    .isEqualTo(expected.getByteAnyMinbytesMikaContentType())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMaxbytesMika()).as("check byteAnyMaxbytesMika").isEqualTo(expected.getByteAnyMaxbytesMika())
            )
            .satisfies(a ->
                assertThat(a.getByteAnyMaxbytesMikaContentType())
                    .as("check byteAnyMaxbytesMika content type")
                    .isEqualTo(expected.getByteAnyMaxbytesMikaContentType())
            )
            .satisfies(a -> assertThat(a.getByteTextMika()).as("check byteTextMika").isEqualTo(expected.getByteTextMika()))
            .satisfies(a ->
                assertThat(a.getByteTextRequiredMika()).as("check byteTextRequiredMika").isEqualTo(expected.getByteTextRequiredMika())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTestServiceImplEntityUpdatableRelationshipsEquals(
        FieldTestServiceImplEntity expected,
        FieldTestServiceImplEntity actual
    ) {
        // empty method
    }
}
