package tech.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MapsIdUserProfileWithDTOAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMapsIdUserProfileWithDTOAllPropertiesEquals(
        MapsIdUserProfileWithDTO expected,
        MapsIdUserProfileWithDTO actual
    ) {
        assertMapsIdUserProfileWithDTOAutoGeneratedPropertiesEquals(expected, actual);
        assertMapsIdUserProfileWithDTOAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMapsIdUserProfileWithDTOAllUpdatablePropertiesEquals(
        MapsIdUserProfileWithDTO expected,
        MapsIdUserProfileWithDTO actual
    ) {
        assertMapsIdUserProfileWithDTOUpdatableFieldsEquals(expected, actual);
        assertMapsIdUserProfileWithDTOUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the derived primary key is set correctly.
     *
     * @param entityToPersist the entity used to persist
     * @param persisted the persisted entity
     */
    public static void assertMapsIdUserProfileWithDTOMapsIdRelationshipPersistedValue(
        MapsIdUserProfileWithDTO entityToPersist,
        MapsIdUserProfileWithDTO persisted
    ) {
        // Validate the id for MapsId, the ids must be same
        assertThat(entityToPersist.getUser().getId()).isEqualTo(persisted.getId());
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMapsIdUserProfileWithDTOAutoGeneratedPropertiesEquals(
        MapsIdUserProfileWithDTO expected,
        MapsIdUserProfileWithDTO actual
    ) {
        assertThat(actual)
            .as("Verify MapsIdUserProfileWithDTO auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMapsIdUserProfileWithDTOUpdatableFieldsEquals(
        MapsIdUserProfileWithDTO expected,
        MapsIdUserProfileWithDTO actual
    ) {
        assertThat(actual)
            .as("Verify MapsIdUserProfileWithDTO relevant properties")
            .satisfies(a -> assertThat(a.getDateOfBirth()).as("check dateOfBirth").isEqualTo(expected.getDateOfBirth()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMapsIdUserProfileWithDTOUpdatableRelationshipsEquals(
        MapsIdUserProfileWithDTO expected,
        MapsIdUserProfileWithDTO actual
    ) {
        // empty method
    }
}
