import dayjs from 'dayjs/esm';

import { EnumFieldClass } from 'app/entities/enumerations/enum-field-class.model';
import { EnumRequiredFieldClass } from 'app/entities/enumerations/enum-required-field-class.model';

import { IFieldTestPaginationEntity, NewFieldTestPaginationEntity } from './field-test-pagination-entity.model';

export const sampleWithRequiredData: IFieldTestPaginationEntity = {
  id: 24965,
  stringRequiredAlice: 'yowza hmph',
  integerRequiredAlice: 6689,
  longRequiredAlice: 30106,
  floatRequiredAlice: 8610.3,
  doubleRequiredAlice: 14505.53,
  bigDecimalRequiredAlice: 24665.79,
  localDateRequiredAlice: dayjs('2016-02-08'),
  instanteRequiredAlice: dayjs('2016-02-08T00:20'),
  zonedDateTimeRequiredAlice: dayjs('2016-02-08T00:06'),
  localTimeRequiredAlice: '21:38:00',
  durationRequiredAlice: '1712',
  booleanRequiredAlice: false,
  enumRequiredAlice: 'ENUM_VALUE_2',
  uuidRequiredAlice: 'd62a20d2-1436-4de0-9b86-1e875a0ed921',
  byteImageRequiredAlice: '../fake-data/blob/hipster.png',
  byteImageRequiredAliceContentType: 'unknown',
  byteAnyRequiredAlice: '../fake-data/blob/hipster.png',
  byteAnyRequiredAliceContentType: 'unknown',
  byteTextRequiredAlice: '../fake-data/blob/hipster.txt',
};

export const sampleWithPartialData: IFieldTestPaginationEntity = {
  id: 17553,
  stringAlice: 'merry ack fatally',
  stringRequiredAlice: 'over',
  integerAlice: 21302,
  integerRequiredAlice: 11449,
  longRequiredAlice: 6126,
  floatRequiredAlice: 16645.87,
  floatMaxAlice: 66.7,
  doubleRequiredAlice: 25633.55,
  doubleMinAlice: 16553.16,
  doubleMaxAlice: 90.44,
  bigDecimalRequiredAlice: 14988.69,
  localDateAlice: dayjs('2016-02-08'),
  localDateRequiredAlice: dayjs('2016-02-08'),
  instanteRequiredAlice: dayjs('2016-02-08T10:03'),
  zonedDateTimeAlice: dayjs('2016-02-07T23:11'),
  zonedDateTimeRequiredAlice: dayjs('2016-02-07T20:35'),
  localTimeRequiredAlice: '01:58:00',
  durationAlice: '13761',
  durationRequiredAlice: '31767',
  booleanAlice: false,
  booleanRequiredAlice: true,
  enumRequiredAlice: 'ENUM_VALUE_2',
  uuidAlice: '8125dd05-58eb-4376-84ae-e5217630725a',
  uuidRequiredAlice: '0322eb6a-c657-4aeb-a0b9-62929849aa5f',
  byteImageRequiredAlice: '../fake-data/blob/hipster.png',
  byteImageRequiredAliceContentType: 'unknown',
  byteImageMaxbytesAlice: '../fake-data/blob/hipster.png',
  byteImageMaxbytesAliceContentType: 'unknown',
  byteAnyAlice: '../fake-data/blob/hipster.png',
  byteAnyAliceContentType: 'unknown',
  byteAnyRequiredAlice: '../fake-data/blob/hipster.png',
  byteAnyRequiredAliceContentType: 'unknown',
  byteAnyMinbytesAlice: '../fake-data/blob/hipster.png',
  byteAnyMinbytesAliceContentType: 'unknown',
  byteTextAlice: '../fake-data/blob/hipster.txt',
  byteTextRequiredAlice: '../fake-data/blob/hipster.txt',
};

export const sampleWithFullData: IFieldTestPaginationEntity = {
  id: 17190,
  stringAlice: 'source till',
  stringRequiredAlice: 'scorn quadruple',
  stringMinlengthAlice: 'vainly',
  stringMaxlengthAlice: 'near mockingly',
  stringPatternAlice: undefined,
  integerAlice: 13429,
  integerRequiredAlice: 23401,
  integerMinAlice: 21731,
  integerMaxAlice: 83,
  longAlice: 11557,
  longRequiredAlice: 15904,
  longMinAlice: 19407,
  longMaxAlice: 39,
  floatAlice: 9197.09,
  floatRequiredAlice: 12357.49,
  floatMinAlice: 3805.99,
  floatMaxAlice: 0.84,
  doubleRequiredAlice: 14026.54,
  doubleMinAlice: 28137.98,
  doubleMaxAlice: 52.29,
  bigDecimalRequiredAlice: 31383.71,
  bigDecimalMinAlice: 34.65,
  bigDecimalMaxAlice: 94.03,
  localDateAlice: dayjs('2016-02-08'),
  localDateRequiredAlice: dayjs('2016-02-07'),
  instantAlice: dayjs('2016-02-08T05:05'),
  instanteRequiredAlice: dayjs('2016-02-07T23:39'),
  zonedDateTimeAlice: dayjs('2016-02-08T06:49'),
  zonedDateTimeRequiredAlice: dayjs('2016-02-08T11:01'),
  localTimeAlice: '03:13:00',
  localTimeRequiredAlice: '22:01:00',
  durationAlice: '17108',
  durationRequiredAlice: '9499',
  booleanAlice: true,
  booleanRequiredAlice: false,
  enumAlice: 'ENUM_VALUE_3',
  enumRequiredAlice: 'ENUM_VALUE_3',
  uuidAlice: 'a7fcd3c2-952e-4bf5-99be-e281461ad46a',
  uuidRequiredAlice: '8df6ff93-a203-4c37-9b7f-50c5270d11f2',
  byteImageAlice: '../fake-data/blob/hipster.png',
  byteImageAliceContentType: 'unknown',
  byteImageRequiredAlice: '../fake-data/blob/hipster.png',
  byteImageRequiredAliceContentType: 'unknown',
  byteImageMinbytesAlice: '../fake-data/blob/hipster.png',
  byteImageMinbytesAliceContentType: 'unknown',
  byteImageMaxbytesAlice: '../fake-data/blob/hipster.png',
  byteImageMaxbytesAliceContentType: 'unknown',
  byteAnyAlice: '../fake-data/blob/hipster.png',
  byteAnyAliceContentType: 'unknown',
  byteAnyRequiredAlice: '../fake-data/blob/hipster.png',
  byteAnyRequiredAliceContentType: 'unknown',
  byteAnyMinbytesAlice: '../fake-data/blob/hipster.png',
  byteAnyMinbytesAliceContentType: 'unknown',
  byteAnyMaxbytesAlice: '../fake-data/blob/hipster.png',
  byteAnyMaxbytesAliceContentType: 'unknown',
  byteTextAlice: '../fake-data/blob/hipster.txt',
  byteTextRequiredAlice: '../fake-data/blob/hipster.txt',
};

export const sampleWithNewData: NewFieldTestPaginationEntity = {
  stringRequiredAlice: 'busily quixotic searchingly',
  integerRequiredAlice: 4527,
  longRequiredAlice: 14970,
  floatRequiredAlice: 12701.35,
  doubleRequiredAlice: 14774.2,
  bigDecimalRequiredAlice: 14004.89,
  localDateRequiredAlice: dayjs('2016-02-08'),
  instanteRequiredAlice: dayjs('2016-02-08T07:12'),
  zonedDateTimeRequiredAlice: dayjs('2016-02-08T02:45'),
  localTimeRequiredAlice: '04:19:00',
  durationRequiredAlice: '12342',
  booleanRequiredAlice: true,
  enumRequiredAlice: 'ENUM_VALUE_2',
  uuidRequiredAlice: '3c7c6150-1ed8-40ac-a11b-f1ffc03f05e3',
  byteImageRequiredAlice: '../fake-data/blob/hipster.png',
  byteImageRequiredAliceContentType: 'unknown',
  byteAnyRequiredAlice: '../fake-data/blob/hipster.png',
  byteAnyRequiredAliceContentType: 'unknown',
  byteTextRequiredAlice: '../fake-data/blob/hipster.txt',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
