import dayjs from 'dayjs/esm';

import { EnumFieldClass } from 'app/entities/enumerations/enum-field-class.model';
import { EnumRequiredFieldClass } from 'app/entities/enumerations/enum-required-field-class.model';

import {
  IFieldTestServiceClassAndJpaFilteringEntity,
  NewFieldTestServiceClassAndJpaFilteringEntity,
} from './field-test-service-class-and-jpa-filtering-entity.model';

export const sampleWithRequiredData: IFieldTestServiceClassAndJpaFilteringEntity = {
  id: 4109,
  stringRequiredBob: 'amused if oof',
  integerRequiredBob: 9381,
  longRequiredBob: 28999,
  floatRequiredBob: 29729.41,
  doubleRequiredBob: 13022.42,
  bigDecimalRequiredBob: 16998.18,
  localDateRequiredBob: dayjs('2016-02-08'),
  instanteRequiredBob: dayjs('2016-02-08T03:55'),
  zonedDateTimeRequiredBob: dayjs('2016-02-08T01:40'),
  localTimeRequiredBob: '09:34:00',
  durationRequiredBob: '16380',
  booleanRequiredBob: false,
  enumRequiredBob: 'ENUM_VALUE_2',
  uuidRequiredBob: 'a78e3bca-6f2c-4e4e-b9d2-f86092c8d63b',
  byteImageRequiredBob: '../fake-data/blob/hipster.png',
  byteImageRequiredBobContentType: 'unknown',
  byteAnyRequiredBob: '../fake-data/blob/hipster.png',
  byteAnyRequiredBobContentType: 'unknown',
  byteTextRequiredBob: '../fake-data/blob/hipster.txt',
};

export const sampleWithPartialData: IFieldTestServiceClassAndJpaFilteringEntity = {
  id: 24212,
  stringBob: 'contravene',
  stringRequiredBob: 'muddy fidget',
  integerBob: 3147,
  integerRequiredBob: 28691,
  longRequiredBob: 24468,
  floatRequiredBob: 29010.98,
  floatMaxBob: 70.58,
  doubleRequiredBob: 14715.56,
  bigDecimalRequiredBob: 9199.48,
  bigDecimalMinBob: 4619.63,
  localDateBob: dayjs('2016-02-08'),
  localDateRequiredBob: dayjs('2016-02-07'),
  instantBob: dayjs('2016-02-08T05:11'),
  instanteRequiredBob: dayjs('2016-02-08T16:18'),
  zonedDateTimeRequiredBob: dayjs('2016-02-08T03:51'),
  localTimeBob: '08:26:00',
  localTimeRequiredBob: '17:06:00',
  durationBob: '15356',
  durationRequiredBob: '20263',
  booleanBob: false,
  booleanRequiredBob: true,
  enumRequiredBob: 'ENUM_VALUE_1',
  uuidBob: '8279751c-e02e-4ac9-ac2a-1d1229c3f178',
  uuidRequiredBob: 'f3616692-8c48-4d0f-941a-0f9a6dd65e6d',
  byteImageRequiredBob: '../fake-data/blob/hipster.png',
  byteImageRequiredBobContentType: 'unknown',
  byteAnyBob: '../fake-data/blob/hipster.png',
  byteAnyBobContentType: 'unknown',
  byteAnyRequiredBob: '../fake-data/blob/hipster.png',
  byteAnyRequiredBobContentType: 'unknown',
  byteTextBob: '../fake-data/blob/hipster.txt',
  byteTextRequiredBob: '../fake-data/blob/hipster.txt',
};

export const sampleWithFullData: IFieldTestServiceClassAndJpaFilteringEntity = {
  id: 7166,
  stringBob: 'um bug consequently',
  stringRequiredBob: 'sick joyful',
  stringMinlengthBob: 'everlasting personal aboard',
  stringMaxlengthBob: 'implode',
  stringPatternBob: '1GX',
  integerBob: 27834,
  integerRequiredBob: 17657,
  integerMinBob: 25467,
  integerMaxBob: 32,
  longBob: 21453,
  longRequiredBob: 7366,
  longMinBob: 19683,
  longMaxBob: 8,
  floatBob: 30027.15,
  floatRequiredBob: 831.34,
  floatMinBob: 8662.56,
  floatMaxBob: 81.5,
  doubleRequiredBob: 18889.04,
  doubleMinBob: 19926.34,
  doubleMaxBob: 67.42,
  bigDecimalRequiredBob: 23164.8,
  bigDecimalMinBob: 3345.57,
  bigDecimalMaxBob: 37.67,
  localDateBob: dayjs('2016-02-08'),
  localDateRequiredBob: dayjs('2016-02-08'),
  instantBob: dayjs('2016-02-08T10:51'),
  instanteRequiredBob: dayjs('2016-02-08T07:47'),
  zonedDateTimeBob: dayjs('2016-02-08T06:51'),
  zonedDateTimeRequiredBob: dayjs('2016-02-07T18:43'),
  localTimeBob: '05:56:00',
  localTimeRequiredBob: '15:32:00',
  durationBob: '70',
  durationRequiredBob: '13993',
  booleanBob: false,
  booleanRequiredBob: false,
  enumBob: 'ENUM_VALUE_3',
  enumRequiredBob: 'ENUM_VALUE_1',
  uuidBob: '2ef21b76-5570-4503-842d-bc6729417f93',
  uuidRequiredBob: '17b8a6e8-c2ee-46a8-b408-81a625813bae',
  byteImageBob: '../fake-data/blob/hipster.png',
  byteImageBobContentType: 'unknown',
  byteImageRequiredBob: '../fake-data/blob/hipster.png',
  byteImageRequiredBobContentType: 'unknown',
  byteImageMinbytesBob: '../fake-data/blob/hipster.png',
  byteImageMinbytesBobContentType: 'unknown',
  byteImageMaxbytesBob: '../fake-data/blob/hipster.png',
  byteImageMaxbytesBobContentType: 'unknown',
  byteAnyBob: '../fake-data/blob/hipster.png',
  byteAnyBobContentType: 'unknown',
  byteAnyRequiredBob: '../fake-data/blob/hipster.png',
  byteAnyRequiredBobContentType: 'unknown',
  byteAnyMinbytesBob: '../fake-data/blob/hipster.png',
  byteAnyMinbytesBobContentType: 'unknown',
  byteAnyMaxbytesBob: '../fake-data/blob/hipster.png',
  byteAnyMaxbytesBobContentType: 'unknown',
  byteTextBob: '../fake-data/blob/hipster.txt',
  byteTextRequiredBob: '../fake-data/blob/hipster.txt',
};

export const sampleWithNewData: NewFieldTestServiceClassAndJpaFilteringEntity = {
  stringRequiredBob: 'whether shakily',
  integerRequiredBob: 4110,
  longRequiredBob: 17230,
  floatRequiredBob: 9185.57,
  doubleRequiredBob: 20105.93,
  bigDecimalRequiredBob: 4634.81,
  localDateRequiredBob: dayjs('2016-02-08'),
  instanteRequiredBob: dayjs('2016-02-08T08:55'),
  zonedDateTimeRequiredBob: dayjs('2016-02-08T09:13'),
  localTimeRequiredBob: '07:27:00',
  durationRequiredBob: '12387',
  booleanRequiredBob: true,
  enumRequiredBob: 'ENUM_VALUE_3',
  uuidRequiredBob: 'f3f872c3-8b24-45b9-87d4-c37fdd36230e',
  byteImageRequiredBob: '../fake-data/blob/hipster.png',
  byteImageRequiredBobContentType: 'unknown',
  byteAnyRequiredBob: '../fake-data/blob/hipster.png',
  byteAnyRequiredBobContentType: 'unknown',
  byteTextRequiredBob: '../fake-data/blob/hipster.txt',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
