import dayjs from 'dayjs/esm';

import { EnumFieldClass } from 'app/entities/enumerations/enum-field-class.model';
import { EnumRequiredFieldClass } from 'app/entities/enumerations/enum-required-field-class.model';

import { IFieldTestServiceImplEntity, NewFieldTestServiceImplEntity } from './field-test-service-impl-entity.model';

export const sampleWithRequiredData: IFieldTestServiceImplEntity = {
  id: 7391,
  stringRequiredMika: 'considering inasmuch majestically',
  integerRequiredMika: 4962,
  longRequiredMika: 16038,
  floatRequiredMika: 15068.5,
  doubleRequiredMika: 23967.89,
  bigDecimalRequiredMika: 26276.51,
  localDateRequiredMika: dayjs('2016-02-08'),
  instanteRequiredMika: dayjs('2016-02-07T19:13'),
  zonedDateTimeRequiredMika: dayjs('2016-02-07T19:13'),
  localTimeRequiredMika: '09:13:00',
  durationRequiredMika: '19832',
  booleanRequiredMika: true,
  enumRequiredMika: 'ENUM_VALUE_2',
  uuidRequiredMika: '4ce3651e-7267-405f-98a8-1f24c8b4e8fc',
  byteImageRequiredMika: '../fake-data/blob/hipster.png',
  byteImageRequiredMikaContentType: 'unknown',
  byteAnyRequiredMika: '../fake-data/blob/hipster.png',
  byteAnyRequiredMikaContentType: 'unknown',
  byteTextRequiredMika: '../fake-data/blob/hipster.txt',
};

export const sampleWithPartialData: IFieldTestServiceImplEntity = {
  id: 20980,
  stringMika: 'moist wring abandoned',
  stringRequiredMika: 'narrow hm beneath',
  stringMaxlengthMika: 'helplessly',
  integerMika: 6523,
  integerRequiredMika: 22714,
  integerMinMika: 20118,
  integerMaxMika: 31,
  longMika: 27614,
  longRequiredMika: 16049,
  longMinMika: 15291,
  longMaxMika: 28,
  floatMika: 11044.37,
  floatRequiredMika: 19106.34,
  floatMaxMika: 42.31,
  doubleRequiredMika: 6311.76,
  doubleMaxMika: 36.92,
  bigDecimalRequiredMika: 9388.98,
  bigDecimalMinMika: 24914.98,
  bigDecimalMaxMika: 75.49,
  localDateRequiredMika: dayjs('2016-02-08'),
  instanteRequiredMika: dayjs('2016-02-08T17:28'),
  zonedDateTimeMika: dayjs('2016-02-08T12:47'),
  zonedDateTimeRequiredMika: dayjs('2016-02-08T08:12'),
  localTimeRequiredMika: '20:06:00',
  durationRequiredMika: '19930',
  booleanRequiredMika: true,
  enumRequiredMika: 'ENUM_VALUE_3',
  uuidRequiredMika: '4f4f94bd-8dd8-4772-a375-a8d940f4c008',
  byteImageRequiredMika: '../fake-data/blob/hipster.png',
  byteImageRequiredMikaContentType: 'unknown',
  byteImageMinbytesMika: '../fake-data/blob/hipster.png',
  byteImageMinbytesMikaContentType: 'unknown',
  byteImageMaxbytesMika: '../fake-data/blob/hipster.png',
  byteImageMaxbytesMikaContentType: 'unknown',
  byteAnyMika: '../fake-data/blob/hipster.png',
  byteAnyMikaContentType: 'unknown',
  byteAnyRequiredMika: '../fake-data/blob/hipster.png',
  byteAnyRequiredMikaContentType: 'unknown',
  byteAnyMinbytesMika: '../fake-data/blob/hipster.png',
  byteAnyMinbytesMikaContentType: 'unknown',
  byteAnyMaxbytesMika: '../fake-data/blob/hipster.png',
  byteAnyMaxbytesMikaContentType: 'unknown',
  byteTextMika: '../fake-data/blob/hipster.txt',
  byteTextRequiredMika: '../fake-data/blob/hipster.txt',
};

export const sampleWithFullData: IFieldTestServiceImplEntity = {
  id: 30433,
  stringMika: 'er aw',
  stringRequiredMika: 'until whether knickers',
  stringMinlengthMika: 'corral apprehensive by',
  stringMaxlengthMika: 'failing',
  stringPatternMika: 'z',
  integerMika: 19262,
  integerRequiredMika: 895,
  integerMinMika: 2621,
  integerMaxMika: 43,
  longMika: 15073,
  longRequiredMika: 30181,
  longMinMika: 2453,
  longMaxMika: 3,
  floatMika: 6519.11,
  floatRequiredMika: 26047.04,
  floatMinMika: 13208.5,
  floatMaxMika: 24.77,
  doubleRequiredMika: 28004.49,
  doubleMinMika: 15079.64,
  doubleMaxMika: 37.56,
  bigDecimalRequiredMika: 17808.81,
  bigDecimalMinMika: 20017.38,
  bigDecimalMaxMika: 82.74,
  localDateMika: dayjs('2016-02-08'),
  localDateRequiredMika: dayjs('2016-02-08'),
  instantMika: dayjs('2016-02-08T00:46'),
  instanteRequiredMika: dayjs('2016-02-07T23:42'),
  zonedDateTimeMika: dayjs('2016-02-08T07:26'),
  zonedDateTimeRequiredMika: dayjs('2016-02-08T15:22'),
  localTimeMika: '01:13:00',
  localTimeRequiredMika: '13:01:00',
  durationMika: '14672',
  durationRequiredMika: '29998',
  booleanMika: false,
  booleanRequiredMika: false,
  enumMika: 'ENUM_VALUE_1',
  enumRequiredMika: 'ENUM_VALUE_3',
  uuidMika: 'fd8dedea-4aad-4d66-941a-d539abb41e2c',
  uuidRequiredMika: '29b17e9e-c444-4c39-b7b5-7149213caf15',
  byteImageMika: '../fake-data/blob/hipster.png',
  byteImageMikaContentType: 'unknown',
  byteImageRequiredMika: '../fake-data/blob/hipster.png',
  byteImageRequiredMikaContentType: 'unknown',
  byteImageMinbytesMika: '../fake-data/blob/hipster.png',
  byteImageMinbytesMikaContentType: 'unknown',
  byteImageMaxbytesMika: '../fake-data/blob/hipster.png',
  byteImageMaxbytesMikaContentType: 'unknown',
  byteAnyMika: '../fake-data/blob/hipster.png',
  byteAnyMikaContentType: 'unknown',
  byteAnyRequiredMika: '../fake-data/blob/hipster.png',
  byteAnyRequiredMikaContentType: 'unknown',
  byteAnyMinbytesMika: '../fake-data/blob/hipster.png',
  byteAnyMinbytesMikaContentType: 'unknown',
  byteAnyMaxbytesMika: '../fake-data/blob/hipster.png',
  byteAnyMaxbytesMikaContentType: 'unknown',
  byteTextMika: '../fake-data/blob/hipster.txt',
  byteTextRequiredMika: '../fake-data/blob/hipster.txt',
};

export const sampleWithNewData: NewFieldTestServiceImplEntity = {
  stringRequiredMika: 'instructive',
  integerRequiredMika: 14421,
  longRequiredMika: 9257,
  floatRequiredMika: 6939.05,
  doubleRequiredMika: 12495.15,
  bigDecimalRequiredMika: 8878.78,
  localDateRequiredMika: dayjs('2016-02-08'),
  instanteRequiredMika: dayjs('2016-02-08T04:26'),
  zonedDateTimeRequiredMika: dayjs('2016-02-08T16:31'),
  localTimeRequiredMika: '15:30:00',
  durationRequiredMika: '23063',
  booleanRequiredMika: false,
  enumRequiredMika: 'ENUM_VALUE_3',
  uuidRequiredMika: 'b27a9a47-d2a1-4009-a75e-8eaa2ac6e6bd',
  byteImageRequiredMika: '../fake-data/blob/hipster.png',
  byteImageRequiredMikaContentType: 'unknown',
  byteAnyRequiredMika: '../fake-data/blob/hipster.png',
  byteAnyRequiredMikaContentType: 'unknown',
  byteTextRequiredMika: '../fake-data/blob/hipster.txt',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
