#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: N2FkNDFkMDMxODdlYTMyNjJjOTkzNzJlNmNjZjkwNGQzMzY1MjQ3OGZmZTdmZmE5YWNjY2Y3ZTM4NDMxYTM3MzY4YWI4ZTVlYjRhMmYxMmMxNDA5NTBmYjg5ZDZkNWUzMTkwNw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
