#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NTkyNDNiMGNjYmFhODU0NzZjODZiMjU5MmI1NGQwMGJmZDI3MGZhNDJlY2Q1MjI0MmExY2Q4NDg1MDg4ODA0OGRhYjBmN2Q5NjVjMDdiNzk5ZjYxMmVkYjUxYTM1Y2YzYjA2Zg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
