package com.mycompany.myapp.app.child.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomPackageChildAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomPackageChildAllPropertiesEquals(CustomPackageChild expected, CustomPackageChild actual) {
        assertCustomPackageChildAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomPackageChildAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomPackageChildAllUpdatablePropertiesEquals(CustomPackageChild expected, CustomPackageChild actual) {
        assertCustomPackageChildUpdatableFieldsEquals(expected, actual);
        assertCustomPackageChildUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomPackageChildAutoGeneratedPropertiesEquals(CustomPackageChild expected, CustomPackageChild actual) {
        assertThat(actual)
            .as("Verify CustomPackageChild auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomPackageChildUpdatableFieldsEquals(CustomPackageChild expected, CustomPackageChild actual) {
        assertThat(actual)
            .as("Verify CustomPackageChild relevant properties")
            .satisfies(a -> assertThat(a.getChildName()).as("check childName").isEqualTo(expected.getChildName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomPackageChildUpdatableRelationshipsEquals(CustomPackageChild expected, CustomPackageChild actual) {
        assertThat(actual)
            .as("Verify CustomPackageChild relationships")
            .satisfies(a ->
                assertThat(a.getCustomPackageParent()).as("check customPackageParent").isEqualTo(expected.getCustomPackageParent())
            );
    }
}
