import dayjs from 'dayjs/esm';

import { EnumFieldClass } from 'app/entities/enumerations/enum-field-class.model';
import { EnumRequiredFieldClass } from 'app/entities/enumerations/enum-required-field-class.model';

import {
  IFieldTestMapstructAndServiceClassEntity,
  NewFieldTestMapstructAndServiceClassEntity,
} from './field-test-mapstruct-and-service-class-entity.model';

export const sampleWithRequiredData: IFieldTestMapstructAndServiceClassEntity = {
  id: 30894,
  stringRequiredEva: 'farm phooey',
  integerRequiredEva: 31078,
  longRequiredEva: 31024,
  floatRequiredEva: 23397.45,
  doubleRequiredEva: 17474.7,
  bigDecimalRequiredEva: 24200.23,
  localDateRequiredEva: dayjs('2016-02-08'),
  instanteRequiredEva: dayjs('2016-02-07T21:51'),
  zonedDateTimeRequiredEva: dayjs('2016-02-08T13:21'),
  localTimeRequiredEva: '21:58:00',
  durationRequiredEva: '9847',
  booleanRequiredEva: true,
  enumRequiredEva: 'ENUM_VALUE_2',
  uuidRequiredEva: 'c5796e76-55fe-4d88-acca-0fa9f0a2d97f',
  byteImageRequiredEva: '../fake-data/blob/hipster.png',
  byteImageRequiredEvaContentType: 'unknown',
  byteAnyRequiredEva: '../fake-data/blob/hipster.png',
  byteAnyRequiredEvaContentType: 'unknown',
  byteTextRequiredEva: '../fake-data/blob/hipster.txt',
};

export const sampleWithPartialData: IFieldTestMapstructAndServiceClassEntity = {
  id: 8752,
  stringRequiredEva: 'hm heighten mammoth',
  stringMaxlengthEva: 'gee',
  integerRequiredEva: 25448,
  integerMinEva: 17591,
  integerMaxEva: 49,
  longEva: 23441,
  longRequiredEva: 22202,
  longMaxEva: 92,
  floatRequiredEva: 27709.48,
  doubleRequiredEva: 6785.59,
  doubleMinEva: 13698.68,
  bigDecimalRequiredEva: 20863.48,
  bigDecimalMinEva: 14400.89,
  localDateRequiredEva: dayjs('2016-02-07'),
  instantEva: dayjs('2016-02-08T13:37'),
  instanteRequiredEva: dayjs('2016-02-07T21:16'),
  zonedDateTimeRequiredEva: dayjs('2016-02-08T01:15'),
  localTimeRequiredEva: '00:56:00',
  durationRequiredEva: '21461',
  booleanRequiredEva: false,
  enumEva: 'ENUM_VALUE_1',
  enumRequiredEva: 'ENUM_VALUE_1',
  uuidRequiredEva: 'fedc01c8-12c4-4959-9f85-dcf8d35548dc',
  byteImageEva: '../fake-data/blob/hipster.png',
  byteImageEvaContentType: 'unknown',
  byteImageRequiredEva: '../fake-data/blob/hipster.png',
  byteImageRequiredEvaContentType: 'unknown',
  byteAnyRequiredEva: '../fake-data/blob/hipster.png',
  byteAnyRequiredEvaContentType: 'unknown',
  byteTextRequiredEva: '../fake-data/blob/hipster.txt',
};

export const sampleWithFullData: IFieldTestMapstructAndServiceClassEntity = {
  id: 25850,
  stringEva: 'phew',
  stringRequiredEva: 'intermesh bah',
  stringMinlengthEva: 'dishonor',
  stringMaxlengthEva: 'enlightened than',
  stringPatternEva: 'i7VE',
  integerEva: 12403,
  integerRequiredEva: 28084,
  integerMinEva: 22210,
  integerMaxEva: 84,
  longEva: 5627,
  longRequiredEva: 23811,
  longMinEva: 19808,
  longMaxEva: 24,
  floatEva: 13729.98,
  floatRequiredEva: 18607.46,
  floatMinEva: 22268.61,
  floatMaxEva: 24.89,
  doubleRequiredEva: 23397.99,
  doubleMinEva: 16625.57,
  doubleMaxEva: 60.02,
  bigDecimalRequiredEva: 22705.54,
  bigDecimalMinEva: 11576.53,
  bigDecimalMaxEva: 27.14,
  localDateEva: dayjs('2016-02-08'),
  localDateRequiredEva: dayjs('2016-02-08'),
  instantEva: dayjs('2016-02-07T23:34'),
  instanteRequiredEva: dayjs('2016-02-07T19:23'),
  zonedDateTimeEva: dayjs('2016-02-08T06:44'),
  zonedDateTimeRequiredEva: dayjs('2016-02-08T07:27'),
  localTimeEva: '20:19:00',
  localTimeRequiredEva: '11:56:00',
  durationEva: '27411',
  durationRequiredEva: '19228',
  booleanEva: true,
  booleanRequiredEva: true,
  enumEva: 'ENUM_VALUE_3',
  enumRequiredEva: 'ENUM_VALUE_3',
  uuidEva: 'ac393a03-45b0-420e-ba62-2fbff9953bf5',
  uuidRequiredEva: '13360076-8723-45f0-ac7c-abcadc0fab01',
  byteImageEva: '../fake-data/blob/hipster.png',
  byteImageEvaContentType: 'unknown',
  byteImageRequiredEva: '../fake-data/blob/hipster.png',
  byteImageRequiredEvaContentType: 'unknown',
  byteImageMinbytesEva: '../fake-data/blob/hipster.png',
  byteImageMinbytesEvaContentType: 'unknown',
  byteImageMaxbytesEva: '../fake-data/blob/hipster.png',
  byteImageMaxbytesEvaContentType: 'unknown',
  byteAnyEva: '../fake-data/blob/hipster.png',
  byteAnyEvaContentType: 'unknown',
  byteAnyRequiredEva: '../fake-data/blob/hipster.png',
  byteAnyRequiredEvaContentType: 'unknown',
  byteAnyMinbytesEva: '../fake-data/blob/hipster.png',
  byteAnyMinbytesEvaContentType: 'unknown',
  byteAnyMaxbytesEva: '../fake-data/blob/hipster.png',
  byteAnyMaxbytesEvaContentType: 'unknown',
  byteTextEva: '../fake-data/blob/hipster.txt',
  byteTextRequiredEva: '../fake-data/blob/hipster.txt',
};

export const sampleWithNewData: NewFieldTestMapstructAndServiceClassEntity = {
  stringRequiredEva: 'yahoo pillory although',
  integerRequiredEva: 24617,
  longRequiredEva: 5119,
  floatRequiredEva: 18503.2,
  doubleRequiredEva: 29571.77,
  bigDecimalRequiredEva: 7710.08,
  localDateRequiredEva: dayjs('2016-02-08'),
  instanteRequiredEva: dayjs('2016-02-07T23:18'),
  zonedDateTimeRequiredEva: dayjs('2016-02-08T06:26'),
  localTimeRequiredEva: '17:43:00',
  durationRequiredEva: '26273',
  booleanRequiredEva: false,
  enumRequiredEva: 'ENUM_VALUE_3',
  uuidRequiredEva: '3d368565-40e2-48ac-b348-b9734b935f57',
  byteImageRequiredEva: '../fake-data/blob/hipster.png',
  byteImageRequiredEvaContentType: 'unknown',
  byteAnyRequiredEva: '../fake-data/blob/hipster.png',
  byteAnyRequiredEvaContentType: 'unknown',
  byteTextRequiredEva: '../fake-data/blob/hipster.txt',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
