package com.mycompany.myapp.app.custom.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CustomPackageParentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomPackageParentAllPropertiesEquals(CustomPackageParent expected, CustomPackageParent actual) {
        assertCustomPackageParentAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomPackageParentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomPackageParentAllUpdatablePropertiesEquals(CustomPackageParent expected, CustomPackageParent actual) {
        assertCustomPackageParentUpdatableFieldsEquals(expected, actual);
        assertCustomPackageParentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomPackageParentAutoGeneratedPropertiesEquals(CustomPackageParent expected, CustomPackageParent actual) {
        assertThat(actual)
            .as("Verify CustomPackageParent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomPackageParentUpdatableFieldsEquals(CustomPackageParent expected, CustomPackageParent actual) {
        assertThat(actual)
            .as("Verify CustomPackageParent relevant properties")
            .satisfies(a -> assertThat(a.getParentName()).as("check parentName").isEqualTo(expected.getParentName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomPackageParentUpdatableRelationshipsEquals(CustomPackageParent expected, CustomPackageParent actual) {
        // empty method
    }
}
